;;;; brush.lisp — brush typography (docs/style/STYLE_STORM_DESIGN.md §4.4): kanji and romaji drawn as filled glyph
;;;; outlines in the UI batch. glyphs.lisp (generated by tools/glyph-bake.py from the OFL font Yuji Syuku) holds each
;;;; glyph as a few simple polygons; BRUSH-INIT (a :load step) ear-clips them into triangles once.
;;;; A caption is a BCAP: a vertical column of kanji (+ an optional second, smaller column), a small romaji reading,
;;;; an optional chapter line, and a direction mark (Bankai's compass: a white glyph in a black box) or a red hanko (Kikon names
;;;; only). Three layouts: :cine (a cinematic's title, 50-70 % of the frame height, bleeding off the top when long),
;;;; :callout (a gameplay SP / technique name at its user's side of the screen) and :results (the 勝 stamp). It is
;;;; stamped in on twos (scale 1.8 -> 1.15 -> 1, a drawn shake, an ink splash) and sliced out (Phase 6: BCAP-EXIT, or a
;;;; timed caption's last 0.3 s: a brush cut through the column, the halves sliding apart). DRAW-BCAP conses nothing.
(in-package :duel)

;;; ---------------------------------------------------------------- glyphs
(defstruct (glyph (:constructor make-glyph (adv tris)))
  (adv 1f0 :type single-float)               ; advance, em
  (tris (make-f32 0) :type f32vec))          ; x y per corner (em, y down from the em box's top), 3 corners a triangle
(defvar *glyphs* (make-hash-table) "Char code -> GLYPH (BRUSH-INIT).")

(defun ear-clip (v)
  "Triangles of the simple polygon V (a vector x0 y0 x1 y1 ... of integers, wound positive with y down) as a list
of corner indices, 3 per triangle. Ear clipping, O(n^2), exact integer tests (coordinates < 2000: the products fit
a fixnum). A polygon whose holes were bridged in (the cut's two end vertices repeated) works: a vertex lying on an
ear's own corner does not block the ear. Collinear corners are dropped without a triangle."
  (let* ((n (floor (length v) 2))
         (xs (make-array n :element-type 'fixnum)) (ys (make-array n :element-type 'fixnum))
         (nx (make-array n :element-type 'fixnum)) (pv (make-array n :element-type 'fixnum))
         (tris '()) (left n) (i 0) (miss 0))
    (declare (fixnum n left i miss) (type (simple-array fixnum (*)) xs ys nx pv))
    (dotimes (k n) (setf (aref xs k) (svref v (* 2 k)) (aref ys k) (svref v (1+ (* 2 k)))
                         (aref nx k) (mod (1+ k) n) (aref pv k) (mod (+ k n -1) n)))
    (locally (declare (optimize (speed 3) (safety 0)))
      (flet ((cross (a b c)
               (declare (fixnum a b c))
               (the fixnum (- (the fixnum (* (the fixnum (- (aref xs b) (aref xs a))) (the fixnum (- (aref ys c) (aref ys a)))))
                              (the fixnum (* (the fixnum (- (aref ys b) (aref ys a))) (the fixnum (- (aref xs c) (aref xs a)))))))))
        (declare (inline cross))
        (flet ((ear-p (a b c)
                 (declare (fixnum a b c))
                 (do ((p (aref nx c) (aref nx p))) ((= p a) t)
                   (declare (fixnum p))
                   (let ((px (aref xs p)) (py (aref ys p)))
                     (declare (fixnum px py))
                     (unless (or (and (= px (aref xs a)) (= py (aref ys a))) (and (= px (aref xs b)) (= py (aref ys b)))
                                 (and (= px (aref xs c)) (= py (aref ys c))))
                       (when (and (>= (cross a b p) 0) (>= (cross b c p) 0) (>= (cross c a p) 0))
                         (return nil)))))))
          (loop while (> left 2) do
            (let* ((a (aref pv i)) (c (aref nx i)) (cr (cross a i c)))
              (declare (fixnum a c cr))
              (if (or (zerop cr) (and (plusp cr) (ear-p a i c)) (> miss left))   ; (> miss left): no ear in a whole lap
                  (progn (when (plusp cr) (push (list a i c) tris))
                         (setf (aref nx a) c (aref pv c) a left (1- left) i c miss 0))
                  (setf i c miss (1+ miss))))))))
    (loop for tri in (nreverse tris) append tri)))

(defun brush-init ()
  "Startup (:load) step: triangulate every glyph of *GLYPH-OUTLINES* into *GLYPHS*. Logs the count and the
area check: the triangles must cover each polygon exactly (BAD > 0 means a broken outline: re-bake)."
  (let ((ntri 0) (bad '()) (t0 (get-internal-real-time)))
    (dolist (g *glyph-outlines*)
      (destructuring-bind (code adv &rest polys) g
        (let ((out '()))
          (dolist (p polys)
            (let* ((v (coerce p 'simple-vector)) (n (floor (length v) 2)) (ix (ear-clip v)) (sum 0)
                   (twice (loop for k below n for j = (mod (+ k n -1) n)
                                sum (- (* (svref v (* 2 j)) (svref v (1+ (* 2 k)))) (* (svref v (* 2 k)) (svref v (1+ (* 2 j))))))))
              (loop for (a b c) on ix by #'cdddr
                    do (incf sum (- (* (- (svref v (* 2 b)) (svref v (* 2 a))) (- (svref v (1+ (* 2 c))) (svref v (1+ (* 2 a)))))
                                    (* (- (svref v (1+ (* 2 b))) (svref v (1+ (* 2 a)))) (- (svref v (* 2 c)) (svref v (* 2 a))))))
                       (dolist (k (list a b c)) (push (/ (svref v (* 2 k)) 1000.0) out) (push (/ (svref v (1+ (* 2 k))) 1000.0) out)))
              (unless (= sum twice) (push (code-char code) bad))))
          (incf ntri (floor (length out) 6))
          (setf (gethash code *glyphs*) (make-glyph (/ adv 1000.0) (coerce (nreverse out) 'f32vec))))))
    (log-msg "brush: ~d glyphs, ~d triangles, ~d bad polygons~@[ (~{~a~})~], ~d ms" (hash-table-count *glyphs*) ntri (length bad) bad
             (round (* 1000 (- (get-internal-real-time) t0)) internal-time-units-per-second))))

(defun brush-width (str &optional (gap 0.0))
  "Width in em of STR set horizontally with GAP em between letters (a space is 0.35 em)."
  (loop for ch across str
        sum (if (char= ch #\Space) 0.35 (let ((g (gethash (char-code ch) *glyphs*))) (if g (+ gap (glyph-adv g)) 0.0)))))

(defun brush-cells (str)
  "Height in em of STR set vertically (a space is half a cell)."
  (loop for ch across str sum (if (member ch '(#\Space #\、)) 0.5 1.0)))

;;; ---------------------------------------------------------------- zero-cons drawing (macros for DEFUN-FAST code)
(declaim (type f32vec *bclip*))
(defvar *bclip* (make-f32 13)
  "The slice exit's clip (DRAW-BCAP; 0 B): [0] 0 = off, +1 / -1 = keep the side n.p >= c / <= c of the cut, [1 2] n (unit,
px), [3] c, [4 5] the kept half's slide (px); [6..12] %GLYPH-TRIS-CLIP's arguments x y sz r g b a.")

(defun-fast %glyph-tris-clip (tv)
  "%GLYPH-TRIS for the glyph triangles TV cut by *BCLIP*'s line: each triangle clipped to the kept side (0-2 triangles),
slid by the half's offset."
  (declare (type f32vec tv))
  (let* ((c *bclip*) (sg (aref c 0)) (nx (aref c 1)) (ny (aref c 2)) (cc (aref c 3)) (ox (aref c 4)) (oy (aref c 5))
         (gx (aref c 6)) (gy (aref c 7)) (gs (aref c 8)) (cr (aref c 9)) (cg (aref c 10)) (cb (aref c 11)) (ca (aref c 12))
         (nt (floor (length tv) 6)))
    (declare (type f32vec c) (single-float sg nx ny cc ox oy gx gy gs cr cg cb ca) (fixnum nt))
    (with-ui-verts (d o (* 6 nt))
      (dotimes (k nt)
        (let* ((q (* 6 k)) (x0 (+ gx (* gs (aref tv q)))) (y0 (+ gy (* gs (aref tv (+ q 1)))))
               (x1 (+ gx (* gs (aref tv (+ q 2))))) (y1 (+ gy (* gs (aref tv (+ q 3)))))
               (x2 (+ gx (* gs (aref tv (+ q 4))))) (y2 (+ gy (* gs (aref tv (+ q 5)))))
               (d0 (* sg (- (+ (* nx x0) (* ny y0)) cc))) (d1 (* sg (- (+ (* nx x1) (* ny y1)) cc)))
               (d2 (* sg (- (+ (* nx x2) (* ny y2)) cc))))
          (declare (fixnum q) (single-float x0 y0 x1 y1 x2 y2 d0 d1 d2))
          (macrolet ((tri (ax ay bx by cx cy)
                       `(progn (uvtx (+ ,ax ox) (+ ,ay oy) cr cg cb ca) (uvtx (+ ,bx ox) (+ ,by oy) cr cg cb ca)
                               (uvtx (+ ,cx ox) (+ ,cy oy) cr cg cb ca)))
                     (cuts (((ax ay ad) (bx by bd) (cx cy cd)) &body body)  ; P = A->B and Q = A->C on the line
                       `(let* ((%u (/ ,ad (- ,ad ,bd))) (%v (/ ,ad (- ,ad ,cd)))
                               (px (+ ,ax (* (- ,bx ,ax) %u))) (py (+ ,ay (* (- ,by ,ay) %u)))
                               (qx (+ ,ax (* (- ,cx ,ax) %v))) (qy (+ ,ay (* (- ,cy ,ay) %v))))
                          (declare (single-float %u %v px py qx qy))
                          ,@body))
                     (one (a b c) `(cuts (,a ,b ,c) (tri ,(first a) ,(second a) px py qx qy)))       ; A in: its corner
                     (two (a b c) `(cuts (,a ,b ,c) (tri px py ,(first b) ,(second b) ,(first c) ,(second c))   ; A out
                                         (tri px py ,(first c) ,(second c) qx qy))))
            (let ((in (+ (if (>= d0 0f0) 1 0) (if (>= d1 0f0) 2 0) (if (>= d2 0f0) 4 0))))
              (declare (fixnum in))
              (case in
                (7 (tri x0 y0 x1 y1 x2 y2))
                (1 (one (x0 y0 d0) (x1 y1 d1) (x2 y2 d2))) (2 (one (x1 y1 d1) (x2 y2 d2) (x0 y0 d0)))
                (4 (one (x2 y2 d2) (x0 y0 d0) (x1 y1 d1)))
                (6 (two (x0 y0 d0) (x1 y1 d1) (x2 y2 d2))) (5 (two (x1 y1 d1) (x2 y2 d2) (x0 y0 d0)))
                (3 (two (x2 y2 d2) (x0 y0 d0) (x1 y1 d1)))))))))
    nil))

(defmacro %glyph-tris (tris x y sz r g b a)
  "Queue the triangles TRIS (a glyph's f32vec), the em box's top left at (X Y), SZ px per em, colour (R G B A); cut
and slid by *BCLIP* while a caption slices out."
  `(let* ((tv ,tris) (gx ,x) (gy ,y) (gs ,sz) (cr ,r) (cg ,g) (cb ,b) (ca ,a) (nv (floor (length tv) 2)) (%cl *bclip*))
     (declare (type f32vec tv %cl) (single-float gx gy gs cr cg cb ca) (fixnum nv))
     (if (/= (aref %cl 0) 0f0)
         (progn (setf (aref %cl 6) gx (aref %cl 7) gy (aref %cl 8) gs (aref %cl 9) cr (aref %cl 10) cg (aref %cl 11) cb
                      (aref %cl 12) ca)
                (%glyph-tris-clip tv))
         (with-ui-verts (d o nv)
           (dotimes (k nv)
             (uvtx (+ gx (* gs (aref tv (* 2 k)))) (+ gy (* gs (aref tv (1+ (* 2 k))))) cr cg cb ca))))))

(declaim (type f32vec *panel-box*))
(defvar *panel-box* (make-f32 8)
  "The HUD's two side panels this frame, per side x0 y0 x1 y1 in px (hud.lisp HUD-SIDE fills them; 0 when not drawn):
the gameplay callouts, the side words and the brush callout columns keep clear of them (Phase 5).")
(declaim (type f32vec *band*))
(defvar *band* (fv 0.1 0.82 0.08 0.9)
  "Portrait (docs/duel/DUEL_MOBILE_DESIGN.md P2), fractions of the window height (onehand.lisp DECK-UPDATE): [0 1] the frame
the portrait camera fits the fighters into (under P2's HUD block, down to *PT-FRAME-BOTTOM*: the thumb may cover their
feet, the user's decision 2026-09-27); [2] the bottom of P2's block at the top, [3] the top of P1's block at the bottom.")
(defmacro panel-hit (x0 y0 x1 y1)
  "The side (0 / 1) of the first HUD panel (*PANEL-BOX*) the box (X0 Y0 X1 Y1) overlaps, or NIL. Float forms; 0 B."
  `(let* ((%pb *panel-box*) (%x0 ,x0) (%y0 ,y0) (%x1 ,x1) (%y1 ,y1))
     (declare (type f32vec %pb) (single-float %x0 %y0 %x1 %y1))
     (cond ((and (< %x0 (aref %pb 2)) (< (aref %pb 0) %x1) (< %y0 (aref %pb 3)) (< (aref %pb 1) %y1)) 0)
           ((and (< %x0 (aref %pb 6)) (< (aref %pb 4) %x1) (< %y0 (aref %pb 7)) (< (aref %pb 5) %y1)) 1))))

(declaim (type f32vec *bcap-box*))
(defvar *bcap-box* (make-f32 4) "DRAW-BCAP: the union of the em boxes it drew this call (x0 y0 x1 y1, px).")

(defmacro %brush-run (str x y sz vertical gap r g b a)
  "Queue string STR from (X Y) (the first em box's top left), SZ px per em: down one em per char (VERTICAL) or
right by the advance + GAP em. A space is half a cell (0.35 em across); a char with no glyph is skipped."
  `(let* ((s ,str) (px ,x) (py ,y) (sz ,sz) (gp ,gap) (rr ,r) (rg ,g) (rb ,b) (ra ,a) (bb *bcap-box*))
     (declare (simple-string s) (single-float px py sz gp rr rg rb ra) (type f32vec bb))
     (dotimes (i (length s))
       (let* ((ch (schar s i)) (gl (and (char/= ch #\Space) (gethash (char-code ch) *glyphs*))))
         (if gl
             (symbol-macrolet ((ax (* sz (the single-float (glyph-adv gl)))))   ; (a bound, unused float would box)
               (when (and ,vertical (char= ch #\、))           ; a vertical comma: half a cell, in its top right
                 (setf px (+ px (* 0.55f0 sz)) py (- py (* 0.55f0 sz))))
               (%glyph-tris (glyph-tris gl) px py sz rr rg rb ra)
               (setf (aref bb 0) (f-min (aref bb 0) px) (aref bb 1) (f-min (aref bb 1) py)      ; the glyph's em box
                     (aref bb 2) (f-max (aref bb 2) (+ px (if ,vertical sz ax))) (aref bb 3) (f-max (aref bb 3) (+ py sz)))
               (if ,vertical
                   (if (char= ch #\、) (setf px (- px (* 0.55f0 sz)) py (+ py (* 1.05f0 sz))) (setf py (+ py sz)))
                   (setf px (+ px ax (* sz gp)))))
             (if ,vertical (setf py (+ py (* 0.5f0 sz))) (setf px (+ px (* 0.35f0 sz)))))))))

(defmacro %brush-box (x y w h r g b a)
  "A solid box (hanko, mark box, rules)."
  `(let* ((x0 ,x) (y0 ,y) (x1 (+ x0 ,w)) (y1 (+ y0 ,h)) (cr ,r) (cg ,g) (cb ,b) (ca ,a))
     (declare (single-float x0 y0 x1 y1 cr cg cb ca))
     (with-ui-verts (d o 6)
       (uvtx x0 y0 cr cg cb ca) (uvtx x1 y0 cr cg cb ca) (uvtx x1 y1 cr cg cb ca)
       (uvtx x0 y0 cr cg cb ca) (uvtx x1 y1 cr cg cb ca) (uvtx x0 y1 cr cg cb ca))))

;;; ---------------------------------------------------------------- captions
(defstruct (bcap (:constructor %make-bcap))
  "A brush caption (see the file header). F: [0] start (fx clock) [1] seconds shown (0 = until replaced)
[2] main column cells [3] second column cells [4] reading width (em, 0.25 em letter gap) [5] chapter line width
[6] the column's centre as a fraction of the screen width (0 = the layout's) [7] the slice exit's start (fx clock; 0 = none,
BCAP-EXIT)."
  (kanji "" :type simple-string) (kanji2 nil) (reading nil) (sub nil) (mark nil)
  (layout :cine) (side 0 :type fixnum) (ink nil) (hanko nil)
  (splash nil)                                ; (cx cy r seed) boxed once per window size: UI-INK-SPLASH's arguments
  (splash-wh -1 :type fixnum)                 ; ... for this window (w * 10000 + h)
  (warned nil)                                ; a glyph was drawn off the screen (logged once)
  (hud-warned nil)                            ; a callout column was drawn over a HUD panel (logged once)
  (f (make-f32 8) :type f32vec))

(defun make-bcap (kanji &key kanji2 reading sub mark (layout :cine) (side 0) ink hanko (secs 0.0))
  "A caption starting now (see BCAP). SIDE 0 / 1: the left / right third (:cine) or that player's side (:callout);
INK: black glyphs (on a white card), else white; HANKO: the red Kikon seal; MARK: a direction glyph string (東 西 南 北)."
  (let* ((c (%make-bcap :kanji (coerce kanji 'simple-string) :kanji2 kanji2 :reading reading :sub sub :mark mark
                        :layout layout :side side :ink ink :hanko hanko))
         (f (bcap-f c)))
    (setf (aref f 0) (fx-clock) (aref f 1) (f32 secs)
          (aref f 2) (f32 (+ (brush-cells kanji) (if mark 1.15 0.0))) (aref f 3) (f32 (if kanji2 (brush-cells kanji2) 0.0))
          (aref f 4) (f32 (if reading (brush-width reading 0.25) 0.0)) (aref f 5) (f32 (if sub (brush-width sub 0.3) 0.0)))
    c))

(defun bcap-restart (c)
  "Stamp caption C in again from now."
  (setf (aref (bcap-f c) 0) (fx-clock) (aref (bcap-f c) 7) 0f0)
  c)

(defun bcap-exit (c)
  "Caption C slices out from now (DRAW-BCAP: a brush cut through the column, the halves slide apart and fade, 0.3 s)."
  (when (<= (aref (bcap-f c) 7) 0f0) (setf (aref (bcap-f c) 7) (fx-clock)))
  c)

(defun bcap-splash-args (c cx cy r w h)
  "C's splash arguments for this window, boxed once per window size (a DEFUN-FAST call boxes its float arguments)."
  (let ((wh (+ (* w 10000) h)))
    (unless (= wh (bcap-splash-wh c))
      (setf (bcap-splash-wh c) wh
            (bcap-splash c) (list (f32 cx) (f32 cy) (f32 r) (f32 (mod (* 7.31 (aref (bcap-f c) 0)) 97.0)))))
    (bcap-splash c)))

(defun bcap-off-screen (c w h)
  "Log once that caption C drew a glyph outside the W x H screen (*BCAP-BOX*; tests/style-4-checks.py greps it)."
  (unless (bcap-warned c)
    (setf (bcap-warned c) t)
    (log-msg "brush: caption ~a off the ~dx~d screen: ~{~,1f~^ ~}" (bcap-kanji c) w h (coerce *bcap-box* 'list))))

(defun-fast draw-bcap (c w h)
  "Draw caption C on a W x H screen (see the file header). The block (mark, column, hanko, reading; the second
column beside it) is sized to fit between the layout's top and bottom lines, the stamp's zoom is capped so it stays
inside them, the reading and the chapter line shrink to fit their half of the screen. Returns T while it is shown."
  (declare (fixnum w h))
  (let* ((f (bcap-f c)) (ww (i->f w)) (hh (i->f h)) (age (- (fx-clock) (aref f 0))) (secs (aref f 1))
         (layout (bcap-layout c)) (cine (eq layout :cine)) (res (eq layout :results)) (right (= (bcap-side c) 1))
         (d (f->i (* 12f0 age)))                                          ; drawings on twos (12 a second)
         (ex (cond ((> (aref f 7) 0f0) (- (fx-clock) (aref f 7)))          ; the slice exit: BCAP-EXIT, or a timed
                   ((> secs 0f0) (- age (- secs 0.3f0))) (t -1f0)))          ; caption's last 0.3 s
         (exiting (>= ex 0f0)) (de (if exiting (f->i (* 12f0 ex)) 0))
         (a (if exiting (f-clamp (/ (- 0.3f0 ex) 0.12f0) 0f0 1f0) 1f0))
         (n (f-max 1f0 (aref f 2))) (n2 (aref f 3)) (hk (bcap-hanko c)) (rd (bcap-reading c))
         (top (cond (res (* 0.03f0 hh)) (cine (* 0.1f0 hh))         ; a callout: under both HUD panels
                    (t (f-max (* 0.27f0 hh) (+ (f-max (if (= (aref *panel-box* 1) 0f0) (aref *panel-box* 3) 0f0)   ; top panels
                                                      (if (= (aref *panel-box* 5) 0f0) (aref *panel-box* 7) 0f0))
                                               (* 0.012f0 hh))))))
         (tall (> hh ww))                                                  ; portrait (P2): a callout keeps over the deck
         (bot (cond (res (* 0.265f0 hh)) (cine (if (bcap-sub c) (* 0.84f0 hh) (* 0.895f0 hh)))
                    (tall (* hh (aref *band* 1))) (t (* 0.9f0 hh))))
         (ls (if cine (* 0.034f0 hh) (* 0.026f0 hh))) (lsh (if rd (* 1.05f0 ls) 0f0))
         (nb (+ (f-max (+ n (if hk 0.58f0 0f0)) (if (> n2 0f0) (+ 0.35f0 (* 0.42f0 n2)) 0f0)) (if rd 0.15f0 0f0)))   ; em of the block
         (sz (f-min (f-min (cond (cine (* 0.24f0 hh)) (res (* 0.2f0 hh)) (t (* 0.075f0 hh))) (/ (- bot top lsh) nb))
                    (if tall (* ww (if cine 0.36f0 0.3f0)) 1f9)))                ; portrait: at most 0.36 of the width (§4.3)
         (bh (+ (* sz nb) lsh))
         (k (f-min (cond ((= d 0) (if cine 1.8f0 1.4f0)) ((= d 1) (if cine 1.15f0 1.1f0)) (t 1f0)) (/ (- bot top) bh)))   ; the stamp
         (sx (case d (1 (* 0.012f0 hh)) (2 (* -0.008f0 hh)) (3 (* 0.004f0 hh)) (t 0f0)))    ; its drawn shake
         (ink (bcap-ink c)) (gr (if ink 0.03f0 0.96f0)) (gb (if ink 0.047f0 0.94f0)) (pr (if ink 0.96f0 0.03f0)) (pb (if ink 0.94f0 0.047f0))
         (ksz (* k sz)) (w2 (if (> n2 0f0) (* 0.483f0 ksz) 0f0))          ; the second column's width + gap
         (cx (cond ((> (aref f 6) 0f0) (* ww (aref f 6)))
                   (cine (if right (* 0.83f0 ww) (* 0.17f0 ww)))
                   (right (- ww (* 0.045f0 ww) (* 0.5f0 sz))) (t (+ (* 0.045f0 ww) (* 0.5f0 sz)))))
         (kx (f-clamp (+ sx (- cx (* 0.5f0 ksz))) (+ (* 0.02f0 ww) (if right w2 0f0)) (- (* 0.98f0 ww) ksz (if right 0f0 w2))))
         (ky (f-max top (f-min (- (+ top (* 0.5f0 bh)) (* 0.5f0 k bh)) (- bot (* k bh))))) (yy ky) (yb ky)
         (bb *bcap-box*))
    (declare (type f32vec f bb) (fixnum d de)
             (single-float ww hh age secs ex a n n2 top bot ls lsh nb sz bh k sx gr gb pr pb ksz w2 cx kx ky yy yb))
    (declare (ignorable tall))
    (when (or (and (> secs 0f0) (> age secs)) (>= ex 0.3f0)) (return-from draw-bcap nil))
    (setf (aref bb 0) 1f9 (aref bb 1) 1f9 (aref bb 2) -1f9 (aref bb 3) -1f9)
    (when (and (>= d 1) (or cine res) (not exiting))                     ; the ink splash, from drawing 1: beside the
      (let ((sp (if (= (bcap-splash-wh c) (+ (* w 10000) h)) (bcap-splash c)   ; column's head (results: right of 勝)
                    (bcap-splash-args c (cond (res (+ cx (* 0.5f0 sz) (* 0.38f0 sz))) (right (+ cx (* 0.62f0 sz))) (t (- cx (* 0.62f0 sz))))
                                      (+ top (* (if res 0.3f0 0.2f0) sz)) (* (if res 0.12f0 0.26f0) sz) w h))))
        (ui-ink-splash (first sp) (second sp) (third sp) (fourth sp) (if ink '(0.03 0.03 0.047 1) '(0.96 0.96 0.94 1)) (1- d))))
    (when (bcap-mark c)                                                  ; the direction mark: a white glyph in a black
      (let* ((bs (* 0.95f0 ksz)) (bx (+ kx (* 0.025f0 ksz))) (fr (f-max 1f0 (* 0.03f0 bs))))   ; box, a white frame
        (declare (single-float bs bx fr))                                ; round it (it reads on a black card too)
        (unless exiting                                                  ; (the slice exit cuts the column alone)
          (%brush-box (- bx fr) (- yy fr) (+ bs fr fr) (+ bs fr fr) 0.96f0 0.96f0 0.94f0 a)
          (%brush-box bx yy bs bs 0.03f0 0.03f0 0.047f0 a)
          (%brush-run (the simple-string (bcap-mark c)) (+ bx (* 0.1f0 bs)) (+ yy (* 0.1f0 bs)) (* 0.8f0 bs) t 0f0 0.96f0 0.96f0 0.94f0 a))
        (setf yy (+ yy (* 1.15f0 ksz)))))
    (let ((y0 yy))
      (declare (single-float y0))
      (macrolet ((columns ()                                             ; the column (+ its ink shadow) and the second
                   `(progn                                               ; column, toward the frame's middle
                      (unless ink                                        ; white glyphs: an ink shadow for the scene
                        (%brush-run (bcap-kanji c) (+ kx (* 0.04f0 ksz)) (+ y0 (* 0.04f0 ksz)) ksz t 0f0 pr pr pb (* 0.8f0 a)))
                      (%brush-run (bcap-kanji c) kx y0 ksz t 0f0 gr gr gb a)
                      (when (> n2 0f0)
                        (let* ((s2 (* 0.42f0 ksz)) (x2 (if right (- kx (* 1.15f0 s2)) (+ kx ksz (* 0.15f0 s2)))) (y2 (+ ky (* 0.35f0 ksz))))
                          (declare (single-float s2 x2 y2))
                          (unless ink (%brush-run (the simple-string (bcap-kanji2 c)) (+ x2 (* 0.05f0 s2)) (+ y2 (* 0.05f0 s2)) s2 t 0f0 pr pr pb (* 0.8f0 a)))
                          (%brush-run (the simple-string (bcap-kanji2 c)) x2 y2 s2 t 0f0 gr gr gb a)
                          (setf yb (+ y2 (* s2 n2))))))))
        (if (not exiting)
            (columns)
            ;; the slice exit (Phase 6): a brush cut rising left to right through the column's middle; the two halves
            ;; slide apart along it on twos (drawings DE 0..3) and fade over the last 0.12 s; the cut stroke shows 2 drawings
            (let* ((cl *bclip*) (mx (+ kx (* 0.5f0 ksz))) (my (+ y0 (* 0.5f0 ksz (- n (if (bcap-mark c) 1.15f0 0f0))))) (ux 0.866f0) (uy -0.5f0) (nx 0.5f0) (ny 0.866f0)
                   (sl (* ksz (+ 0.1f0 (* 0.25f0 (i->f de))))) (sp (* ksz 0.04f0 (+ 1f0 (i->f de)))))
              (declare (type f32vec cl) (single-float mx my ux uy nx ny sl sp))
              (setf (aref cl 1) nx (aref cl 2) ny (aref cl 3) (+ (* nx mx) (* ny my)))
              (setf (aref cl 0) 1f0 (aref cl 4) (+ (* sl ux) (* sp nx)) (aref cl 5) (+ (* sl uy) (* sp ny)))
              (columns)
              (setf (aref cl 0) -1f0 (aref cl 4) (- 0f0 (* sl ux) (* sp nx)) (aref cl 5) (- 0f0 (* sl uy) (* sp ny)))
              (columns)
              (setf (aref cl 0) 0f0)
              (when (< de 2)                                             ; the cut: a long thin spindle along the line
                (let* ((hl (* 1.3f0 ksz)) (hw (* ksz (if (= de 0) 0.04f0 0.018f0))))
                  (declare (single-float hl hw))
                  (with-ui-verts (dv o 6)
                    (uvtx (- mx (* hl ux)) (- my (* hl uy)) gr gr gb a) (uvtx (+ mx (* hw nx)) (+ my (* hw ny)) gr gr gb a)
                    (uvtx (+ mx (* hl ux)) (+ my (* hl uy)) gr gr gb a)
                    (uvtx (- mx (* hl ux)) (- my (* hl uy)) gr gr gb a) (uvtx (+ mx (* hl ux)) (+ my (* hl uy)) gr gr gb a)
                    (uvtx (- mx (* hw nx)) (- my (* hw ny)) gr gr gb a))))))))
    (setf yy (+ yy (* ksz (- n (if (bcap-mark c) 1.15f0 0f0)))))
    (when (and hk (not exiting))                                         ; the red seal: 鬼 knocked out of BLOOD red
      (let* ((hs (* 0.46f0 ksz)) (hx (+ kx (* 0.5f0 (- ksz hs)))) (hy (+ yy (* 0.12f0 ksz))))
        (declare (single-float hs hx hy))
        (%brush-box hx hy hs hs 0.816f0 0.063f0 0.11f0 a)
        (%brush-run "鬼" (+ hx (* 0.1f0 hs)) (+ hy (* 0.1f0 hs)) (* 0.8f0 hs) t 0f0 0.96f0 0.95f0 0.93f0 a)
        (setf yy (+ hy hs))))
    (when (and rd (not exiting))                                         ; the reading, small and letter-spaced, fit to
      (let* ((room (cond (res (* 0.3f0 ww)) (right (- (+ kx ksz) (* 0.51f0 ww))) (t (- (* 0.49f0 ww) kx))))   ; its half
             (rs (f-min ls (/ room (f-max 1f0 (aref f 4))))) (rw (* rs (aref f 4)))
             (rx (cond (res (- cx (* 0.5f0 rw))) (right (- (+ kx ksz) rw)) (t kx)))
             (ry (+ (f-max yy yb) (* 0.15f0 ksz))))
        (declare (single-float room rs rw rx ry))
        (unless (and ink (or cine res))
          (%brush-run (the simple-string rd) (+ rx (* 0.06f0 rs)) (+ ry (* 0.06f0 rs)) rs nil 0.25f0 pr pr pb (* 0.8f0 a)))
        (%brush-run (the simple-string rd) rx ry rs nil 0.25f0 gr gr gb a)))
    (when (and (bcap-sub c) (not exiting))                              ; the chapter line at the foot of its half: — SUB —
      (let* ((ls (f-min (* 0.024f0 hh) (/ (* 0.44f0 ww) (+ (aref f 5) 4f0)))) (tw (* ls (aref f 5))) (rl (* 1.6f0 ls))
             (x (if right (- (* 0.95f0 ww) tw rl (* 0.2f0 ls)) (+ (* 0.05f0 ww) rl (* 0.5f0 ls)))) (y (* 0.868f0 hh)))
        (declare (single-float ls tw x y rl))
        (%brush-box (- x rl (* 0.5f0 ls)) (+ y (* 0.52f0 ls)) rl (* 0.07f0 ls) gr gr gb a)
        (%brush-run (the simple-string (bcap-sub c)) x y ls nil 0.3f0 gr gr gb a)
        (%brush-box (+ x tw (* 0.2f0 ls)) (+ y (* 0.52f0 ls)) rl (* 0.07f0 ls) gr gr gb a)))
    (when (or (< (aref bb 0) -0.5f0) (< (aref bb 1) -0.5f0) (> (aref bb 2) (+ ww 0.5f0)) (> (aref bb 3) (+ hh 0.5f0)))
      (bcap-off-screen c w h))
    (when (and (eq layout :callout) (not (bcap-hud-warned c)) (panel-hit (aref bb 0) (aref bb 1) (aref bb 2) (aref bb 3)))
      (setf (bcap-hud-warned c) t)                                        ; tests/style-5-checks.py greps it
      (log-msg "brush: caption ~a over the HUD on the ~dx~d screen" (bcap-kanji c) w h))
    t))

;;; ---------------------------------------------------------------- one line of brush Latin (callouts, big words)
(defvar *line-widths* (make-hash-table :test 'eq) "String -> its width in em (LINE-WIDTH), cached: the strings are constants.")
(defun line-width (str)
  "STR's width in em as BRUSH-LINE sets it (a boxed float cached per string object: 0 B after the first call)."
  (or (gethash str *line-widths*) (setf (gethash str *line-widths*) (f32 (brush-width str 0.06)))))

(declaim (type f32vec *bl*))
(defvar *bl* (make-f32 8) "BRUSH-LINE's arguments: x (the line's centre) y (the caps' middle) em r g b a, [7] its width in em.")

(defun-fast brush-line (str)
  "One line of brush Latin STR (a move callout, a big word) from *BL*: centred on x, the caps' middle at y, EM px per
em, colour (r g b a), over an ink backing (4 diagonal copies: it reads on the mid-grey plaza too); *BL*[7] =
LINE-WIDTH of STR. 0 B."
  (let* ((v *bl*) (em (aref v 2)) (x (- (aref v 0) (* 0.5f0 em (aref v 7)))) (y (- (aref v 1) (* 0.53f0 em)))
         (o (f-max 1f0 (* 0.035f0 em))) (a (aref v 6)) (sa (* 0.85f0 a)))
    (declare (type f32vec v) (single-float em x y o a sa))
    (%brush-run (the simple-string str) (+ x o) (+ y o) em nil 0.06f0 0.03f0 0.03f0 0.047f0 sa)
    (%brush-run (the simple-string str) (- x o) (+ y o) em nil 0.06f0 0.03f0 0.03f0 0.047f0 sa)
    (%brush-run (the simple-string str) (+ x o) (- y o) em nil 0.06f0 0.03f0 0.03f0 0.047f0 sa)
    (%brush-run (the simple-string str) (- x o) (- y o) em nil 0.06f0 0.03f0 0.03f0 0.047f0 sa)
    (%brush-run (the simple-string str) x y em nil 0.06f0 (aref v 3) (aref v 4) (aref v 5) a))
  nil)

(defun set-line (x y em color &optional (alpha 1.0))
  "Fill *BL* for BRUSH-LINE: centre X, caps' middle Y, EM px, COLOR (r g b [a]) times ALPHA."
  (let ((v *bl*))
    (setf (aref v 0) (f32 x) (aref v 1) (f32 y) (aref v 2) (f32 em) (aref v 3) (f32 (first color))
          (aref v 4) (f32 (second color)) (aref v 5) (f32 (third color))
          (aref v 6) (f32 (* alpha (if (cdddr color) (fourth color) 1.0))))))

;;; ---------------------------------------------------------------- names
(defparameter *brush-callouts*
  ;; move -> (kanji reading mark): the gameplay SP / technique names shown as a brush column at the user's side
  ;; (instead of the pixel callout over his head). The Bankai compass (DUEL_DESIGN §6.1) carries its direction.
  '((:ya-shiranui "不知火" "SHIRANUI" nil) (:ya-taimatsu "松明" "TAIMATSU" nil) (:ya-nadegiri "撫斬" "NADEGIRI" nil)
    (:ya-e-kyokko "旭光" "KYOKKO" "東") (:ya-w-shonetsu "焦熱地獄" "SHONETSU JIGOKU" "西")
    (:ya-kyoku "旭日刃" "KYOKUJITSUJIN" "東") (:ya-kaka "火火十万億死大葬陣" "MINAMI: KAKA JUMANOKUSHI DAISOJIN" "南")
    (:ya-tenchi "" "KITA" "北")
    (:ke-buttagiru "ぶった斬る" "BUTTAGIRU" nil) (:ke-charge "俺に斬れねえもんはねえ" "ORE NI KIRENEE MON WA NEE" nil)
    (:ru-tsukishiro "月白" "SOME NO MAI: TSUKISHIRO" "初") (:ru-hakuren "白漣" "TSUGI NO MAI: HAKUREN" "次")
    (:ru-shirafune "白刀" "SAN NO MAI: SHIRAFUNE" "参") (:ru-breaker "這縄" "BAKUDO NO YON: HAINAWA" "縛")
    (:ru-hakuren-50 "白漣" "TSUGI NO MAI: HAKUREN" "次") (:ru-hakuren-0 "白漣" "TSUGI NO MAI: HAKUREN" "次")
    (:ru-shirafune-50 "白刀" "SAN NO MAI: SHIRAFUNE" "参") (:ru-shirafune-0 "白刀" "SAN NO MAI: SHIRAFUNE" "参")
    (:ru-shimobashira "霜柱" "SHIMOBASHIRA" nil) (:ru-hyoshin "氷震" "HYOSHIN" nil) (:ru-reido "零度凍結" "REIDO TOKETSU" nil))
  "Move name -> (kanji reading mark) of its brush callout.")

(defparameter *brush-names* '((:yamamoto "山本元柳斎重國" "YAMAMOTO GENRYUSAI SHIGEKUNI") (:kenpachi "更木剣八" "ZARAKI KENPACHI")
                              (:rukia "朽木ルキア" "KUCHIKI RUKIA"))
  "Character -> his name in kanji and its reading (the intro's columns).")
