;;;; bits.lisp: the native side of parity.py --bits. Loads duel.fas, queues the debug commands, then prints per battle step
;;;; in LO..HI a "B" line: the sim stream's state and both fighters' state, sf and floats as integer-decode-float pairs.
;;;; Usage: ecl --norc --load babylon/tools/parity/bits.lisp -- <duel.fas> <lo> <hi> <cmd>...   (add 2102: turbo off)
(defparameter cl-user::*sg-args* (cdr (member "--" ext:*command-args* :test #'string=)))
(load (first cl-user::*sg-args*) :verbose nil)
(in-package :duel)
(loop for r = (engine::%init-step) until (eql r 0) when (eql r 2) do (ext:quit 2))
(defparameter *lo* (parse-integer (second cl-user::*sg-args*)))
(defparameter *hi* (parse-integer (third cl-user::*sg-args*)))
(dolist (c (cdddr cl-user::*sg-args*)) (engine::simgate-cmd (parse-integer c)))
(defun fb (x) (if (zerop x) "0" (multiple-value-bind (m e s) (integer-decode-float (float x 1f0)) (format nil "~d.~d" (* s m) e))))
(defun side-line (e)
  (let ((f (fighter e)) (p (pos-of e)) (v (motion-vel (motion e))) (k (motion-kb (motion e))) (g (gauges e)))
    (format nil "~a ~d ~{~a~^ ~}" (fighter-state f) (fighter-sf f)
            (mapcar #'fb (list (aref p 0) (aref p 1) (aref p 2) (yaw-of e) (aref v 0) (aref v 1) (aref v 2) (aref k 0) (aref k 2)
                               (fighter-dist f) (gauges-gg g) (gauges-fs g) (gauges-reiatsu g) (gauges-awaken g) (gauges-meter g)
                               (gauges-stun g) (vpad-sx (pilot-vpad (pilot e))) (vpad-sy (pilot-vpad (pilot e))))))))
(engine::%frame)
(loop repeat 100000
      do (engine::%frame)
         (when (and (eq *flow* :battle) (<= *lo* *match-tick* *hi*))
           (format t "B ~d ~d | ~a | ~a~%" *match-tick* (engine::sim-rnd-state) (side-line *p1*) (side-line *p2*)))
      until (or (and (eq *flow* :battle) (> *match-tick* *hi*)) (eq *flow* :results)))
(finish-output)
(ext:quit 0)
