;;;; hud.lisp — minimal combat HUD (GAME_DESIGN §8): HP with damage trail, Raven gauge, combo
;;;; counter + rating, enemy HP bars, OBLITERATE prompt, guard ring, screen effects and the F3
;;;; debug overlay (fps, state, move frame, hit volumes / hurt cylinders as fx lines), and the
;;;; game-flow screens: title, controls, wave banners, boss bar, timer, off-screen chevrons,
;;;; pause, game over, results (state in game.lisp).
(in-package :raven)

(defvar *debug-overlay* nil "F3 toggles.")
(declaim (type f32vec *hud-v*))
(defvar *hud-v* (make-f32 3))

(defun hud-pulse (hz) (+ 0.5 (* 0.5 (sin (* 2 pi hz (elapsed-time))))))

(defun hud-bars (w h s)
  (let* ((hl (health *player*)) (p (pl))
         (x (* 0.03 w)) (y (* 0.04 h)) (bw (* 0.30 w)) (bh (max (* 5 s) (* 0.022 h)))
         (f (max 0.0 (/ (health-hp hl) (health-max-hp hl)))) (tr (/ (player-hp-trail p) (health-max-hp hl))))
    ;; HP (+ damage trail)
    (ui-rect x y bw bh '(0.063 0.063 0.094 0.7))
    (ui-rect x y (* bw (min 1.0 tr)) bh '(0.70 0.07 0.18 1))
    (ui-rect x y (* bw f) bh (if (< f 0.25) (list 1.0 0.29 0.29 (+ 0.6 (* 0.4 (hud-pulse 2.2)))) '(0.91 0.91 0.91 1)))
    (ui-rect-outline (- x 1) (- y 1) (+ bw 2) (+ bh 2) '(1 1 1 0.35))
    (ui-text (format nil "~d" (ceiling (health-hp hl))) (+ x bw (* 6 s)) y :scale s :color '(0.9 0.9 0.95 0.9) :shadow t)
    ;; Raven gauge
    (let* ((ry (* 0.074 h)) (rw (* 0.24 w)) (rh (max (* 3 s) (* 0.014 h))) (g (/ (player-raven p) 100.0))
           (ready (>= (player-raven p) *raven-threshold*)) (form (player-raven-form p))
           (k (if (or ready form) (+ 0.75 (* 0.25 (hud-pulse 3.0))) 0.6)))
      (ui-rect x ry rw rh '(0.063 0.063 0.094 0.7))
      (ui-rect x ry (* rw g) rh (list k (* k 0.12) (* k 0.24) 1))
      (ui-rect (+ x (* rw 0.4)) (- ry 2) 2 (+ rh 4) '(1 1 1 0.8))
      (let ((ex (* 0.012 w)) (ey (+ ry (/ rh 2))) (d (* 4 s)))       ; diamond emblem
        (ui-rect (- ex (/ d 2)) (- ey (/ d 2)) d d (if form '(1 0.12 0.24 1) '(0.6 0.1 0.15 1))))
      (when (and ready (not form))
        (ui-text "[E] RAVEN" (* 0.28 w) (* 0.070 h) :scale s :color '(1 0.3 0.4 1) :shadow t))
      (when form
        (ui-text "RAVEN FORM" (* 0.28 w) (* 0.070 h) :scale s :color '(1 0.12 0.24 1) :shadow t)))))

(defun hud-combo (w h s)
  (let* ((p (pl)) (n (player-combo p)))
    (when (>= n 2)
      (let* ((punch (/ (player-combo-punch p) 0.1)) (sc (round (* s 5 (+ 1 (* 0.3 punch)))))
             (x (* 0.95 w)) (y (* 0.30 h))
             (fade (min 1.0 (/ (player-combo-t p) 0.5))))
        (ui-text (format nil "~d" n) x y :scale sc :align :right :color (list 1 1 1 fade) :shadow t)
        (ui-text "HITS" x (+ y (* sc 8)) :scale (* 2 s) :align :right :color (list 0.8 0.85 0.9 fade) :shadow t)
        (multiple-value-bind (label col)
            (cond ((>= n 80) (values "RAVEN" '(1 0.12 0.24)))
                  ((>= n 50) (values "BRUTAL" '(1 0.17 0.84)))
                  ((>= n 25) (values "GREAT" '(0.1 0.9 1)))
                  ((>= n 10) (values "GOOD" '(0.78 0.82 0.85))))
          (when label
            (ui-text label x (+ y (* sc 8) (* 20 s)) :scale (* 2 s) :align :right
                     :color (list (first col) (second col) (third col) fade) :shadow t)))))))

(defun hud-enemies (s)
  "World-space enemy HP bars (3 s after damage; crippled = red, pulsing) and the OBLITERATE prompt."
  (let* ((w (window-width)) (bw (* 0.06 w)) (bh (max 3 (* 0.006 (window-height)))) (v *hud-v*)
         (best (and (alive-p *player*) (motion-grounded (motion *player*))
                    (pick-target *player* 1.0 0.0 nil :range 4.0 :half 180.0 :pred #'crippled-p))))
    (do-entities (e (hl health) (f fighter))
      (when (enemy-p e)
        (let* ((p (pos-of e)) (top (+ (aref p 1) (body-hurt-h (body-of e)) 0.35)) (crip (fighter-crippled f)))
          (when (and (or (> (health-bar-t hl) 0) crip) (not (eql e *boss*))
                     (world-to-screen v (aref p 0) top (aref p 2)))
            (let* ((x (- (aref v 0) (/ bw 2))) (y (aref v 1)) (f (max 0.0 (/ (health-hp hl) (health-max-hp hl)))))
              (ui-bar x y bw bh f (if crip '(1 0.12 0.24) '(0.91 0.91 0.91)) :bg '(0.06 0.06 0.09 0.7))
              (when crip
                (ui-rect-outline (- x 2) (- y 2) (+ bw 4) (+ bh 4) (list 1 0.12 0.24 (hud-pulse 4))))))
          (when (and (eql e best) (world-to-screen v (aref p 0) (+ top 0.5) (aref p 2)))
            (let ((sc (max 1 (round (* s 2 (+ 1 (* 0.15 (hud-pulse 4))))))))
              (ui-text (if (pad-connected-p) "OBLITERATE [Y]" "OBLITERATE [K]") (aref v 0) (- (aref v 1) (* 10 sc))
                       :scale sc :align :center :color '(1 1 1 1) :shadow '(1 0.12 0.24 1)))))))))

(defun hud-guard-ring ()
  "Guard meter as a ring segment under the player's feet while guarding and below 100."
  (let* ((a *player*) (m (player-guard-meter (pl))))
    (when (and (member (state-of a) '(:guard :parry)) (< m 100))
      (let* ((p (pos-of a)) (x (aref p 0)) (z (aref p 2)) (n (max 1 (round (* 32 (/ m 100)))))
             (low (< m 35)) (r 0.75))
        (dotimes (i n)
          (let ((a0 (* i (/ (* 2 pi) 32))) (a1 (* (1+ i) (/ (* 2 pi) 32))))
            (fx-line (+ x (* r (sin a0))) 0.05 (+ z (* r (cos a0))) (+ x (* r (sin a1))) 0.05 (+ z (* r (cos a1)))
                     0.03 (if low 1.0 0.6) (if low 0.6 0.85) (if low 0.24 1.0) 0.8)))))))

;;; ---------------------------------------------------------------- debug overlay (F3)
(defun dbg-circle (x y z r cr cg cb &optional (n 16))
  (dotimes (i n)
    (let ((a0 (* i (/ (* 2 pi) n))) (a1 (* (1+ i) (/ (* 2 pi) n))))
      (fx-line (+ x (* r (sin a0))) y (+ z (* r (cos a0))) (+ x (* r (sin a1))) y (+ z (* r (cos a1)))
               0.012 cr cg cb 0.8))))

(defun dbg-vol (a v)
  (let* ((p (pos-of a)) (ax (aref p 0)) (ay (aref p 1)) (az (aref p 2)) (yaw (yaw-of a))
         (fx (fwd-x yaw)) (fz (fwd-z yaw)))
    (case (round (aref v 0))
      (0 (let ((r (aref v 1)) (half (aref v 2)))
           (dolist (hy (list (aref v 3) (aref v 4)))
             (let* ((n 12) (y (+ ay hy)))
               (dotimes (i n)
                 (let* ((t0 (+ yaw (- half) (* (/ (* 2 half) n) i))) (t1 (+ t0 (/ (* 2 half) n))))
                   (fx-line (- ax (* r (sin t0))) y (- az (* r (cos t0))) (- ax (* r (sin t1))) y (- az (* r (cos t1)))
                            0.015 1 0.2 0.2 0.9)))
               (when (< half 3.1)
                 (fx-line ax y az (- ax (* r (sin (+ yaw half)))) y (- az (* r (cos (+ yaw half)))) 0.015 1 0.2 0.2 0.9)
                 (fx-line ax y az (- ax (* r (sin (- yaw half)))) y (- az (* r (cos (- yaw half)))) 0.015 1 0.2 0.2 0.9))))))
      (1 (let ((y (+ ay (aref v 3))))
           (fx-line (+ ax (* fx (aref v 1))) y (+ az (* fz (aref v 1))) (+ ax (* fx (aref v 2))) y (+ az (* fz (aref v 2)))
                    (aref v 4) 1 0.2 0.2 0.25)))
      (2 (let ((cx (+ ax (* fx (aref v 1)))) (cy (+ ay (aref v 2))) (cz (+ az (* fz (aref v 1)))))
           (dbg-circle cx cy cz (aref v 3) 1 0.2 0.2)))
      (3 (let ((tg (fighter-target (fighter a))))
           (when (entity-alive-p tg) (let ((q (pos-of tg))) (dbg-circle (aref q 0) (+ (aref q 1) 1.1) (aref q 2) (aref v 1) 1 0.2 0.2))))))))

(defun hud-debug (s)
  (do-entities (a (f fighter) (hl health))
    (when (health-alive hl)
      (let* ((p (pos-of a)) (b (body-of a)) (r (body-hurt-r b)) (hh (body-hurt-h b))
             (inv (if (eql a *player*) (player-invulnerable-p) (> (health-invuln hl) 0))))
        (dbg-circle (aref p 0) (+ (aref p 1) 0.02) (aref p 2) r (if inv 0.3 0.2) (if inv 0.4 1) (if inv 1 0.3))
        (dbg-circle (aref p 0) (+ (aref p 1) hh) (aref p 2) r (if inv 0.3 0.2) (if inv 0.4 1) (if inv 1 0.3))
        (let ((mv (fighter-move f)))
          (when (and (eq (fighter-state f) :move) mv)
            (loop for h across (mv-hits mv)
                  when (and (>= (fighter-sf f) (hd-from h)) (< (fighter-sf f) (hd-to h)))
                    do (dolist (v (hd-vols h)) (dbg-vol a v))))))))
  (let* ((f (fighter *player*)) (mv (fighter-move f)))
    (ui-text (format nil "FPS ~,1f  CONS ~d B/F  DRAWS ~d  PARTS ~d  HITSTOP ~d  SCALE ~,2f/~,2f~%STATE ~a~@[ ~a~] F ~,1f  HP ~,1f  GUARD ~,1f  RAVEN ~,1f"
                     (fps) (round (cons-per-frame)) *draw-count* *plive* *hitstop*
                     (slowmo-scale nil) (slowmo-scale t)
                     (fighter-state f) (and (eq (fighter-state f) :move) mv (mv-name mv)) (fighter-sf f)
                     (health-hp (health *player*)) (player-guard-meter (pl)) (player-raven (pl)))
             (* 8 s) (- (window-height) (* 30 s)) :scale s :color '(0.6 1 0.7 1) :shadow t)))

(defparameter *white* '(1 1 1 1))
(defparameter *dim* '(0.62 0.7 0.82 1))
(defparameter *crimson* '(1 0.12 0.24 1))

(defun big-text (str x y scale color shadow s &key (shear 0.18))
  "Large centred block text (crisp font-pixel blocks, slight italic lean) with a 2 px x UI-scale
offset SHADOW; Y is the text's vertical centre. Shrinks to fit the window width."
  (let* ((w (window-width)) (px (min scale (floor (* 0.92 w) (max 1 (+ 2 (text-width str 1))))))
         (y (- y (* 3.5 px))) (d (* 2 s)))
    (ui-block-text str (+ x d) (+ y d) px :color shadow :shear shear :align :center)
    (ui-block-text str x y px :color color :shear shear :align :center)))

(defun hud-menu (items y0 w h s)
  (let ((sc (* 2 s)) (dy (* 22 s)))
    (loop for it in items for i from 0 do
      (let* ((sel (= i *menu*)) (y (+ (* h y0) (* i dy))) (tw (text-width it sc)))
        (when sel                                     ; crimson bar behind the selection
          (ui-gradient (- (/ w 2) (* 0.5 tw) (* 10 s)) (- y (* 3 s)) (+ (* 0.5 tw) (* 10 s)) (+ (* 7 sc) (* 6 s))
                       '(0.7 0.05 0.12 0.0) '(0.7 0.05 0.12 0.75) :vertical nil)
          (ui-gradient (/ w 2) (- y (* 3 s)) (+ (* 0.5 tw) (* 10 s)) (+ (* 7 sc) (* 6 s))
                       '(0.7 0.05 0.12 0.75) '(0.7 0.05 0.12 0.0) :vertical nil))
        (ui-text it (floor w 2) y :scale sc :align :center :color (if sel *white* '(0.78 0.82 0.88 1)) :shadow t)))))

(defun menu-hint (w y s)
  (ui-text (if (pad-connected-p) "D-PAD SELECT    A CONFIRM    B BACK" "W/S OR ARROWS SELECT    ENTER CONFIRM    ESC BACK")
           (floor w 2) y :scale s :align :center :color *dim*))

(defun title-logo (w h s)
  "RAVEN (white) EDGE (crimson) in leaning block letters on a dark band, a crimson slash drawn
through it, and the subtitle between two rules. Returns the y below the subtitle."
  (let* ((px (max 3 (floor (min (/ (* 0.88 w) 62) (/ (* 0.13 h) 7)))))
         (sh 0.25) (tw (* px (+ 59 (* 7 sh)))) (x0 (/ (- w tw) 2)) (ty (floor (* 0.2 h))) (th (* 7 px))
         (grow (min 1.0 (/ *gt* 0.35))) (sd (max 2 (round px 4))))
    (ui-gradient 0 (- ty (* 4 px)) w (* 7.5 px) '(0.01 0 0.02 0) '(0.01 0 0.02 0.8))
    (ui-gradient 0 (+ ty (* 3.5 px)) w (* 8 px) '(0.01 0 0.02 0.8) '(0.01 0 0.02 0))
    ;; slash: a long thin crimson blade stroke rising left -> right behind the letters
    (let* ((ax (- x0 (* 3 px))) (ay (+ ty th (* 1.2 px))) (bx (+ ax (* grow (+ tw (* 6 px))))) (by (- ay (* grow (+ th (* 2.4 px)))))
           (mx (/ (+ ax bx) 2)) (my (/ (+ ay by) 2)) (len (max 1.0 (sqrt (+ (expt (- bx ax) 2) (expt (- by ay) 2)))))
           (nx (/ (- ay by) len)) (ny (/ (- bx ax) len)) (k (* 0.55 px)) (kc (* 0.12 px)))
      (%ui-poly4 ax ay (- mx (* nx k)) (- my (* ny k)) bx by (+ mx (* nx k)) (+ my (* ny k))
                 '(0.85 0.04 0.12 0.9) '(0.85 0.04 0.12 0.9))
      (ui-block-text "RAVEN" (+ x0 sd) (+ ty sd) px :color '(0 0 0 0.75) :shear sh)
      (ui-block-text "EDGE" (+ x0 (* 36 px) sd) (+ ty sd) px :color '(0 0 0 0.75) :shear sh)
      (ui-block-text "RAVEN" x0 ty px :color *white* :color2 '(0.7 0.74 0.82 1) :shear sh)
      (ui-block-text "EDGE" (+ x0 (* 36 px)) ty px :color '(1 0.25 0.33 1) :color2 '(0.6 0.03 0.09 1) :shear sh)
      (%ui-poly4 ax ay (- mx (* nx kc)) (- my (* ny kc)) bx by (+ mx (* nx kc)) (+ my (* ny kc))   ; white-hot core
                 '(1 0.9 0.92 0.95) '(1 0.9 0.92 0.95)))
    (let* ((sy (+ ty th (* 2.6 px))) (sub "A RAIN-SOAKED BLADE") (sw (text-width sub s)) (cx (/ w 2))
           (rl (* 5 px)) (ry (+ sy (* 3 s))))
      (ui-text sub cx sy :scale s :align :center :color '(0.62 0.7 0.82 1) :shadow t)
      (ui-rect (- cx (* 0.5 sw) (* 3 s) rl) ry rl (max 1 s) '(0.85 0.04 0.12 0.9))
      (ui-rect (+ cx (* 0.5 sw) (* 3 s)) ry rl (max 1 s) '(0.85 0.04 0.12 0.9))
      (+ sy (* 7 s)))))

(defun hud-title (w h s)
  (ui-gradient 0 0 w h '(0.02 0.02 0.05 0.15) '(0.02 0.02 0.05 0.55))
  (let ((by (title-logo w h s)))
    (hud-menu *title-menu* (max 0.56 (/ (+ by (* 26 s)) h)) w h s))
  (let* ((pad (pad-connected-p))
         (keys (if pad "X LIGHT   Y HEAVY   A JUMP   B DODGE   RT GUARD   LT RAVEN"
                   "J/LMB LIGHT   K/RMB HEAVY   SPACE JUMP   SHIFT DODGE   Q GUARD   E RAVEN"))
         (fs (fit-scale keys s (* 0.94 w))))
    (when (audio-locked-p)
      (ui-text "CLICK TO ENABLE SOUND & MOUSE" (floor w 2) (* 0.85 h) :scale (fit-scale "CLICK TO ENABLE SOUND & MOUSE" (* 2 s) (* 0.9 w))
               :align :center :color (list 1 1 1 (+ 0.45 (* 0.55 (hud-pulse 1.2)))) :shadow '(0.7 0.05 0.12 1)))
    (ui-text keys (floor w 2) (- h (* 16 fs)) :scale fs :align :center :color *dim*)))

(defparameter *controls-text*
  '(("MOVE" "WASD" "L-STICK") ("CAMERA" "MOUSE / ARROWS" "R-STICK") ("LIGHT ATTACK" "J / LMB" "X")
    ("HEAVY / OBLITERATE" "K / RMB" "Y") ("JUMP" "SPACE" "A") ("DODGE" "SHIFT / L" "B")
    ("GUARD (TAP = PARRY)" "Q (HOLD)" "RT (HOLD)") ("RAVEN BURST" "E" "LT") ("PAUSE" "ESC / ENTER" "START")))

(defun hud-controls (w h s)
  "Three columns (action / keyboard + mouse / gamepad), scaled to fit the window."
  (ui-rect 0 0 w h '(0.01 0 0.02 0.82))
  (big-text "CONTROLS" (floor w 2) (* 0.12 h) (* 4 s) *white* '(0.7 0.05 0.12 1) s)
  (let* ((sc (max 1 (min (* 2 s) (floor (* 0.92 w) 288) (floor (* 0.62 h) 132))))
         (cw (* 6 sc)) (x0 (/ (- w (* 48 cw)) 2)) (x1 (+ x0 (* 22 cw))) (x2 (+ x0 (* 41 cw)))
         (y0 (* 0.24 h)) (dy (* 11 sc)))
    (ui-text "ACTION" x0 y0 :scale sc :color '(1 0.25 0.33 1))
    (ui-text "KEYBOARD + MOUSE" x1 y0 :scale sc :color '(1 0.25 0.33 1))
    (ui-text "GAMEPAD" x2 y0 :scale sc :color '(1 0.25 0.33 1))
    (ui-rect x0 (+ y0 (* 8.5 sc)) (* 48 cw) (max 1 (floor sc 2)) '(0.85 0.04 0.12 0.7))
    (loop for (a b c) in *controls-text* for i from 1 do
      (let ((y (+ y0 (* 0.6 dy) (* i dy))))
        (when (oddp i) (ui-rect (- x0 (* 2 sc)) (- y (* 2 sc)) (+ (* 48 cw) (* 4 sc)) (* 11 sc) '(1 1 1 0.04)))
        (ui-text a x0 y :scale sc :color *dim*)
        (ui-text b x1 y :scale sc :color *white*)
        (ui-text c x2 y :scale sc :color *white*))))
  (ui-text (if (pad-connected-p) "B BACK" "ESC BACK") (floor w 2) (* 0.9 h) :scale (* 2 s) :align :center
           :color '(1 0.25 0.33 1) :shadow t))

(defun hud-banner (w h s)
  "Wave banner: slides in from x+0.1 with alpha over 0.3 s, holds 1.2 s, out over 0.3 s."
  (when *banner*
    (let ((title (banner-title *banner*)) (sub (banner-sub *banner*)) (t0 (banner-start *banner*)))
      (let* ((age (- (elapsed-time) t0)))
        (if (> age 1.8)
            (setf *banner* nil)
            (let* ((a (cond ((< age 0.3) (/ age 0.3)) ((> age 1.5) (/ (- 1.8 age) 0.3)) (t 1.0)))
                   (x (+ (* 0.5 w) (* 0.1 w (- 1 a) (if (> age 1.5) -1 1)))))
              (ui-rect 0 (* 0.31 h) w (* 0.16 h) (list 0 0 0 (* 0.45 a)))
              (big-text title x (* 0.36 h) (* 6 s) (list 1 1 1 a) (list 0.7 0.07 0.18 a) s)
              (when (plusp (length sub))
                (ui-text sub x (+ (* 0.36 h) (* 29 s)) :scale (* 2 s) :align :center :color (list 0.62 0.7 0.82 a) :shadow t))))))))

(defun hud-boss (w h s)
  (let ((b *boss*))
    (when (and (alive-p b) (not (eq *game* :boss-intro)) (not (eq (state-of b) :spawn)))
      (let* ((x (* 0.2 w)) (y (* 0.9 h)) (bw (* 0.6 w)) (bh (max (* 4 s) (* 0.02 h))) (mx (health-max-hp (health b)))
             (f (max 0.0 (/ (health-hp (health b)) mx))) (tr (min 1.0 (/ *boss-trail* mx)))
             (broken (crippled-p b)))
        (ui-text (if broken "ENRA, THE CRIMSON GENERAL - BROKEN" "ENRA, THE CRIMSON GENERAL") x (- y (* 11 s))
                 :scale s :color (if broken *crimson* *white*) :shadow t)
        (ui-rect x y bw bh '(0.063 0.063 0.094 0.7))
        (ui-rect x y (* bw tr) bh '(0.70 0.07 0.18 1))
        (ui-rect x y (* bw f) bh (if (enra-p2-p b) '(1 0.18 0.28 1) '(0.85 0.8 0.78 1)))
        (ui-rect (+ x (* bw 0.5)) (- y 2) 2 (+ bh 4) '(1 1 1 0.8))
        (ui-rect-outline (- x 1) (- y 1) (+ bw 2) (+ bh 2) '(1 1 1 0.35))))))

(defun hud-chevrons (w h s)
  "Red chevron at the screen edge pointing at an off-screen attacker (0.6 s)."
  (let* ((cam *camera*) (f (camera-forward cam)) (r (camera-right cam)) (eye (camera-eye cam)))
    (do-entities (e (b brain))
      (when (and (enemy-p e) (> (brain-chevron-t b) 0))
        (let* ((p (pos-of e)) (dx (- (aref p 0) (aref eye 0))) (dz (- (aref p 2) (aref eye 2)))
               (sx (+ (* dx (aref r 0)) (* dz (aref r 2)))) (sy (+ (* dx (aref f 0)) (* dz (aref f 2))))
               (a (atan sx sy)) (ux (sin a)) (uy (- (cos a))) (px (- uy)) (py ux)
               (x (+ (* 0.5 w) (* 0.44 w ux))) (y (+ (* 0.5 h) (* 0.4 h uy)))
               (al (min 1.0 (/ (brain-chevron-t b) 0.2))) (sz (* 6 s)) (col (list 1 0.1 0.1 al)))
          (dotimes (i 9)
            (let ((k (* i 4 s)))
              (ui-rect (- (+ x (* px k)) (* ux k) (/ sz 2)) (- (+ y (* py k)) (* uy k) (/ sz 2)) sz sz col)
              (ui-rect (- (- x (* px k)) (* ux k) (/ sz 2)) (- (- y (* py k)) (* uy k) (/ sz 2)) sz sz col))))))))

(defun hud-results (w h s)
  (ui-rect 0 0 w h '(0.01 0.01 0.03 0.72))
  (ui-text "MISSION COMPLETE" (* 0.1 w) (* 0.12 h) :scale (fit-scale "MISSION COMPLETE" (* 5 s) (* 0.8 w)) :color *white* :shadow t)
  (let* ((p (pl))
         (rows (list (list "TIME" (fmt-time *run-time*)) (list "KILLS" (player-kills p)) (list "MAX COMBO" (player-max-combo p))
                     (list "OBLITERATIONS" (player-obliterations p)) (list "DAMAGE TAKEN" (round (player-damage-taken p)))
                     (list "RETRIES" *retries*) (list "SCORE" (final-score)))))
    (loop for (k v) in rows for i from 0 below *result-rows* do
      (let ((y (* h (+ 0.3 (* i 0.075)))))
        (ui-text k (* 0.1 w) y :scale (* 2 s) :color *dim*)
        (ui-text (format nil "~a" v) (* 0.52 w) y :scale (* 2 s) :align :right :color *white* :shadow t)))
    (when (>= *result-rows* 7)
      (let* ((r (final-rank)) (age (- *gt* 2.15)) (punch (max 0.0 (- 1.0 (* 6 age))))
             (col (cond ((string= r "S") '(1 0.76 0.24 1)) ((string= r "A") '(1 0.17 0.84 1))
                        ((string= r "B") '(0.1 0.9 1 1)) (t '(0.62 0.7 0.82 1)))))
        (ui-text "RANK" (* 0.75 w) (* 0.3 h) :scale (* 2 s) :align :center :color *dim*)
        (big-text r (* 0.75 w) (* 0.58 h) (round (* 16 s (+ 1 (* 0.4 punch)))) col '(0 0 0 0.8) s)
        (when (> *gt* 2.4)
          (ui-text "ENTER - TITLE" (floor w 2) (* 0.9 h) :scale (* 2 s) :align :center
                   :color (list 1 1 1 (hud-pulse 1.5))))))))

(defun hud-over (w h s)
  (ui-rect 0 0 w h (list 0.05 0 0.01 (min 0.6 (* 0.6 *gt*))))
  (big-text "YOU HAVE FALLEN" (floor w 2) (* 0.34 h) (* 5 s) '(0.8 0.08 0.18 1) '(0 0 0 0.8) s)
  (hud-menu *over-menu* 0.55 w h s)
  (menu-hint w (* 0.9 h) s))

(defun hud-pause (w h s)
  (ui-rect 0 0 w h '(0 0 0 0.6))
  (big-text "PAUSED" (floor w 2) (* 0.28 h) (* 5 s) *white* '(0.7 0.05 0.12 1) s)
  (hud-menu *pause-menu* 0.45 w h s)
  (menu-hint w (* 0.9 h) s))

(defun hud-letterbox (w h)
  (let ((bh (* 0.1 h)))
    (ui-rect 0 0 w bh '(0 0 0 1))
    (ui-rect 0 (- h bh) w bh '(0 0 0 1))))

(defun hud-draw (dt)
  (let* ((w (window-width)) (h (window-height)) (s (ui-scale)) (a *player*) (g *game*))
    (cond
      ((eq g :title) (unless *controls* (hud-title w h s)))
      (t
       (fx-draw-screen dt (/ (health-hp (health a)) (health-max-hp (health a))) (raven-form-p))
       (when (member g '(:intro :boss-intro :victory)) (hud-letterbox w h))
       (when (eq g :intro)
         (let ((al (max 0.0 (min 1.0 (* 2 (- 2.0 *gt*))))))
           (big-text "RAVEN EDGE" (floor w 2) (* 0.5 h) (* 6 s) (list 1 1 1 al) (list 1 0.12 0.24 al) s)))
       (unless (member g '(:intro :boss-intro :victory :results))
         (hud-bars w h s)
         (hud-combo w h s)
         (hud-enemies s)
         (hud-guard-ring)
         (hud-boss w h s)
         (hud-chevrons w h s)
         (unless *training*
           (ui-text (fmt-time *run-time*) (* 0.95 w) (* 0.04 h) :scale (max 1 (round (* 1.5 s))) :align :right
                    :color '(0.78 0.82 0.85 1) :shadow t)))
       (hud-banner w h s)
       (case g
         (:over (hud-over w h s))
         (:dying (ui-rect 0 0 w h (list 0.05 0 0.01 (* 0.3 *gt*))))
         (:results (hud-results w h s)))
       (when *paused* (hud-pause w h s))
       (when *training*
         (ui-text "TRAINING   T DUMMIES ATTACK   ESC MENU" (- w (* 8 s)) (- h (* 12 s)) :scale s :align :right
                  :color '(0.62 0.7 0.82 0.6)))))
    (when *controls* (hud-controls w h s))
    (when *debug-overlay* (hud-debug s))))
