// vite.config.ts: relative paths (the dist folder works under any URL path, e.g. a Pages subfolder), and sw.js <-
// duel/web/sw.js written at build time with this build's files and a version hashed from them (every build installs a
// fresh cache; everything is served cache-first from ONE version, so the page and its scripts always match).
import { createHash } from 'node:crypto';
import { readdirSync } from 'node:fs';
import { defineConfig, type Plugin } from 'vite';

const sw = (files: string[], version: string) => `// SOUL DUEL's service worker (generated by vite.config.ts from duel/web/sw.js).
var VERSION = 'soulduel-bjs-${version}';
var FILES = ${JSON.stringify(['./', ...files])};
self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(VERSION)
    .then(function (c) { return c.addAll(FILES.map(function (f) { return new Request(f, { cache: 'reload' }); })); })
    .then(function () { return self.skipWaiting(); }));
});
self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys()
    .then(function (ks) { return Promise.all(ks.filter(function (k) { return k.indexOf('soulduel-bjs-') === 0 && k !== VERSION; }).map(function (k) { return caches.delete(k); })); })
    .then(function () { return self.clients.claim(); }));
});
self.addEventListener('fetch', function (e) {
  if (e.request.method !== 'GET' || new URL(e.request.url).origin !== location.origin) return;
  e.respondWith(caches.open(VERSION).then(function (c) {
    return c.match(e.request, { ignoreSearch: true }).then(function (r) { return r || fetch(e.request); });
  }));
});
`;

const serviceWorker = (): Plugin => ({
  name: 'soulduel-sw',
  apply: 'build',
  generateBundle(_o, bundle) {
    const files = [...Object.keys(bundle), ...readdirSync('public')].sort();
    const h = createHash('sha1');
    for (const k of Object.keys(bundle).sort()) { const b = bundle[k]; h.update(k); h.update(b.type === 'chunk' ? b.code : b.source); }
    this.emitFile({ type: 'asset', fileName: 'sw.js', source: sw(files, h.digest('hex').slice(0, 12)) });
  },
});

export default defineConfig({ base: './', plugins: [serviceWorker()] });
