// tuning.ts <- duel/lisp/tuning.lisp (GENERATED by reading the Lisp forms; edit values here, keep names).
// SOUL DUEL's balance knobs in one place. Units: frames are 60 Hz fixed steps, distances metres, speeds m/s,
// angles degrees, Reishi integer points, fractions 0..1. One mutable object: tests may rebind a knob and restore it.
export const T = {
  /** Reishi (health) of every fighter at the start, integer points. 1100 -> 1300 (guard v3, the user's decision 2026-09-26: real human matches ru ... */
  reishiMax: 1300,
  /** Konpaku (soul pips) per fighter, as in RoS; the one at 0 loses. */
  konpakuMax: 9,
  /** Red = Reishi below this fraction of max: the Kikon rush's dash-in follow-up can't be guarded (rules KIKON-FOLLOW-UNGUARDABLE-P; above red he ... */
  redThreshold: 0.3,
  /** Konpaku a Kikon removes (a kit's default :kikon-konpaku). */
  kikonKonpaku: 2,
  /** Konpaku a Kikon removes when the attacker is awakened (the default of an awakened kit). */
  kikonKonpakuAwakened: 3,
  /** A Soul Break (Reishi reached 0) removes the attacker's current Kikon count + this ... */
  soulBreakExtra: 1,
  /** ... but a Kikon never removes more than this (Nozarashi v2 §2.7) ... */
  kikonMaxEvent: 4,
  /** ... and a Soul Break never more than this (the user's decision 2026-09-27: the Soul Break's own cap, so NOMIHOSE's 4 + 1 = 5; a Kikon stays  ... */
  soulBreakMaxEvent: 5,
  /** ... and the strike starts as soon as the opponent is within this range (a blocked strike pushes him 0.6 m back: 2.2 m, still inside both cha ... */
  kikonTrigger: 1.6,
  /** A rush strike that hits with the button held knocks the victim this far back (a short stagger) ... */
  kikonFollowKb: 2.5,
  /** ... for this long (a victim who isn't red; a red one reels until the Kikon lands: KIKON-FOLLOW-STUN) ... */
  kikonFollowStun: 16,
  /** ... while the rusher dashes in after him: its strike (the Kikon) lands this many frames after he can act again, so he can guard it (not red) ... */
  kikonFollowGap: 12,
  /** Default :track (deg/s) of a Kikon rush strike's startup (like the Breaker's dash). */
  kikonTrack: 120.0,
  /** A move's armour (:armor-hits) starts on this move frame (no frame-1 reversals). */
  armorFrom: 6,
  /** After a Kikon / Soul Break both fighters are placed this far apart. */
  resetDistance: 8.0,
  /** Frames of neutral (inputs ignored) after the reset (0.8 s). */
  resetNeutral: 48,
  /** Reiatsu a kit with :reset-reiatsu gets at each reset (Kenpachi). */
  resetReiatsuBonus: 10.0,
  /** Match timer. Time-up: more Konpaku wins, then higher Reishi %, else draw. */
  matchSeconds: 300,
  /** Chip-damage fraction of fire projectiles on block (never kills). */
  chipFire: 0.12,
  /** Frames a button press stays buffered in the vpad. */
  inputBuffer: 10,
  /** Degrees per frame a fighter auto-turns to the opponent (idle/walk/guard). */
  faceRate: 18.0,
  /** Default :track (deg/s turn allowed during startup) of Quick moves. */
  trackQuick: 360.0,
  /** Default :track of Flash, Signature and SP moves. */
  trackHeavy: 60.0,
  /** Default :track of the Breaker dash: a sideways Step from >= 3 m beats it, a back Step doesn't. */
  trackBreaker: 120.0,
  /** Yamamoto's walk / strafe speed. */
  walkYamamoto: 3.2,
  /** Kenpachi's walk / strafe speed. */
  walkKenpachi: 4.4,
  /** Step hop length (stick direction; neutral = back). */
  stepDistance: 2.5,
  /** Step total frames. */
  stepFrames: 24,
  /** Step invulnerable frames, inclusive. */
  stepIframes: [3, 9],
  /** From this Step frame (the hop's slide is over) J cancels the rest of the Step into J1 (the user, 2026-10-02). */
  stepJCancel: 12,
  /** Yamamoto's run (dash) speed: Step held past the hop. */
  runYamamoto: 8.0,
  /** Kenpachi's run speed. */
  runKenpachi: 10.0,
  /** Degrees per second a runner turns toward the stick direction. */
  runTurn: 300.0,
  /** A run toward the opponent stops this close to him. */
  runStop: 1.2,
  /** Frames of braking after Step is released (committed, like recovery). */
  runBrake: 6,
  /** A move started out of a run slides this far along the run (momentum) ... */
  runCarry: 1.0,
  /** ... over this many frames (never past *RUN-STOP* from the opponent). */
  runCarryFrames: 10,
  /** Frames of holding Guard before it blocks. */
  guardRaise: 2,
  /** Guard covers this many degrees in front (while the guard gauge lasts). */
  guardArc: 200.0,
  /** Metres a blocked hit pushes the defender back. */
  blockPushback: 0.6,
  /** A move that touched nothing recovers R + this (a J / K link: the two below). */
  whiffExtra: 6,
  /** A J link (a :quick move) that touched nothing recovers R + this, a single swing with no string after it (docs/DUEL_STRINGS.md §2.2, the user ... */
  whiffExtraJ: 8,
  /** ... and a K link (a :flash move) R + this. */
  whiffExtraK: 12,
  /** Blockstun of a blocked hazard hit (fire wave, Shiranui, pillars): a projectile has no attacker recovery to measure advantage against, so it  ... */
  hazardBlockstun: 14,
  /** On block a string's next link starts this many frames before the current link's recovery ends. With a -2 link this leaves S_eff(next) - 2 fr ... */
  chainLead: 3,
  /** The guard cancel (the user, 2026-10-01): a move whose own hit landed may end in a guard (Guard held) once only this share of its recovery is ... */
  guardCancel: 0.5,
  /** ASSIST (the user, 2026-10-01; docs/DUEL_ASSIST.md): a move the assist pressed deals this x its damage (its Hoho is never perfect): playing i ... */
  assistMult: 0.8,
  /** Frames the AUTO tag shows over a fighter after the assist pressed for him. */
  assistTagFrames: 45,
  /** A J / K string's ender (J3 / K3) that hits pushes its victim at once out of the attacker's J1 (J3) / K1 (K3) reach: that move's reach + its  ... */
  enderPush: 0.05,
  /** ... over this many frames. */
  enderPushFrames: 8,
  /** The O ender off a pushing J3 / K3 dashes at least this many frames ... */
  enderODash: 24,
  /** ... at least this fast (m/s), and on while he still slides (KIKON-RUSH-STEP): it reaches him. */
  enderOSpeed: 16.0,
  /** A move started off a pushing J3 / K3 (L, SP, ORANGE's J1) chases him this fast at most (m/s): the follow-ups start as the hitstop ends, whil ... */
  enderChaseMax: 40.0,
  /** A string's opener (J1 / K1) that HITS dashes its attacker in to this distance from his victim (the user 2026-10-02: the links no longer chas ... */
  stringPullTo: 0.7,
  /** ... over this many frames. */
  stringPullFrames: 6,
  /** A blocked J (a :quick move) leaves its defender this many frames more than its written block advantage (the user, 2026-10-02: J strings alon ... */
  quickBlockAdv: 3,
  /** Damage multiplier of a counter-hit (Breaker / stance hit during startup). */
  counterMult: 1.25,
  /** Extra hitstun frames of a counter-hit. */
  counterStun: 10,
  /** Aura frames before the Breaker dash starts. */
  breakerAura: 12,
  /** Shortest dash (a tapped Breaker) before the strike. */
  breakerDashMin: 12,
  /** Longest dash while the button is held. */
  breakerDashMax: 45,
  /** Dash speed at the start of the dash (m/s)... */
  breakerSpeedMin: 9.0,
  /** ... rising to this at *breaker-dash-max*. */
  breakerSpeedMax: 10.0,
  /** The strike starts when the opponent is within this range (centre to centre; 2.2 until the user's 2026-09-29 rule 防 > J > I > 防, docs/DUEL_ST ... */
  breakerTrigger: 0.95,
  /** Strike startup (the aura brightens over it: the 'hit it now' tell). */
  breakerStartup: 8,
  /** Strike active frames. */
  breakerActive: 4,
  /** Strike recovery. */
  breakerRecovery: 18,
  /** Strike recovery after a whiff. */
  breakerWhiff: 30,
  /** Strike damage on a non-guarding opponent. */
  breakerDamage: 150,
  /** Strike hit reach (2.6 until 2026-09-29): under every form's J1 reach (J beats I, 防 > J > I > 防), and with the thinnest hurt radius (0.34) pa ... */
  breakerReach: 0.7,
  /** Strike slide: a stagger in place (3.0 m knockback until 2026-10-02: the Breaker opens a combo, J1 / K1 cancel off it). */
  breakerKnockback: 0.3,
  /** Stun of a Guard Break. */
  guardBreakStun: 50,
  /** Crumple of a stance broken by a Breaker. */
  stanceBreakStun: 40,
  /** Breaker vs Breaker (both dashing/striking) within this range = CLASH. */
  clashRange: 3.0,
  /** A clash pushes both fighters this far apart ... */
  clashPush: 4.0,
  /** ... and stuns both this long. */
  clashStun: 24,
  /** Slide of a guard-broken fighter. */
  guardBreakKb: 0.8,
  /** Slide of a broken stance. */
  stanceBreakKb: 0.5,
  /** Reiatsu gauge maximum (3 bars). */
  reiatsuMax: 300.0,
  /** One bar. */
  reiatsuBar: 100.0,
  /** Reiatsu per second, always (5 before the flash-step gauge took Hoho and Burst off it: design v3 G.3). */
  reiatsuRegen: 3.0,
  /** Reiatsu per point of damage dealt. */
  reiatsuDealt: 0.08,
  /** Reiatsu per point of damage taken. */
  reiatsuTaken: 0.1,
  /** Bars an SP1 / SP2 costs. */
  costSp: 1,
  /** Bars an SP2 costs in an awakened form. */
  costSpAwakened: 2,
  /** KOSEI: the multiplier's range above 1 (x1 full gauge .. x(1 + this) empty). */
  koseiBonus: 2.0,
  /** KOSEI: Reiatsu per guard point of a paying contact (x m). */
  koseiReiatsu: 0.2,
  /** KOSEI: flash-step per guard point of a paying contact (x m). */
  koseiFs: 0.1,
  /** Flash-step gauge maximum; full at the match start, kept through Kikon resets. */
  fsMax: 100.0,
  /** Flash-step a Hoho costs. */
  fsHoho: 30.0,
  /** Flash-step every burst mode needs to start (the user's "two bars"; the drain is the cost). */
  fsBurst: 70.0,
  /** Flash-step per second ... */
  fsRegen: 3.0,
  /** ... once this many frames passed since the last spend. */
  fsDelay: 60,
  /** Flash-step per point of damage taken (a full 1300 Reishi bar = +39). */
  fsTaken: 0.03,
  /** A perfect Hoho gives this back (net cost 15: it rewards the read). */
  fsRefund: 15.0,
  /** Guard gauge maximum; full at the start and after every Kikon reset (both). */
  ggMax: 100.0,
  /** Guard value (the gauge a blocked hit drains) by move kind; a hitwin / move :guard overrides it. */
  ggKind: { quick: 8, flash: 14, sig: 18, sp: 22, kikon: 20 },
  /** Guard value of a blocked hazard hit without its own :guard. */
  ggHazard: 12,
  /** + this for a string ender (Quick / Flash / Signature with block advantage <= *GG-ENDER-ADV*). */
  ggEnder: 4,
  /** The block advantage that makes a Quick / Flash / Signature an ender. */
  ggEnderAdv: -10,
  /** A Breaker's Guard Break also drains this. */
  ggBreaker: 35,
  /** The gauge refills only after this many frames without a drain (the user: 45 -> 60), counting only frames he is not guarding (GUARD HOLD, gua ... */
  ggDelay: 60,
  /** ... at this per second (the user: 20 -> 12; then, the user's request 2026-09-27 (大幅減少防禦量表的恢復速度): 12 -> 5.5, 46 %) ... */
  ggRegen: 5.5,
  /** ... or this while guardless (the user: 25 -> 14; 2026-09-27: 14 -> 6.5, 46 %; 0 -> 100 in 15.4 s + the delay). */
  ggRegenGuardless: 6.5,
  /** A blocked hit that empties the gauge is still blocked, then the defender reels this long (GUARD CRUSH) and can't guard until the gauge is fu ... */
  guardCrushStun: 40,
  /** Hoho reappears this far behind the opponent, facing him. */
  hohoDistance: 1.6,
  /** Hoho total frames. */
  hohoFrames: 24,
  /** Hoho invulnerable frames, inclusive. */
  hohoIframes: [1, 14],
  /** Frames between two Hohos. */
  hohoLockout: 60,
  /** Perfect Hoho: an opponent hit volume active now or within this many frames (8 -> 12, the user 2026-10-01: a wider timing; still inside the H ... */
  perfectLead: 12,
  /** ... overlapping our hurt cylinder grown by this (radius and height). */
  perfectInflate: 1.0,
  /** Perfect Hoho slow motion, both fighters. */
  perfectSlowmoSeconds: 0.45,
  /** Perfect Hoho time scale. */
  perfectSlowmoScale: 0.25,
  /** The automatic counter strike (can't be Hoho'd or Burst). */
  perfectCounterDamage: 60,
  /** Hitstun of the counter strike. */
  perfectCounterStun: 36,
  /** Frames the perfect-Hoho victim's inputs are locked. */
  perfectLock: 40,
  /** Hoho frame on which the fighter reappears behind the opponent ... */
  hohoAppear: 6,
  /** ... a perfect Hoho's counter swing starts ... */
  hohoCounterPose: 10,
  /** ... and its strike lands. */
  hohoCounterStrike: 14,
  /** Awakening gauge maximum: full = EVOLUTION (once per match). */
  awakenMax: 100.0,
  /** Awakening per point of damage dealt (0.05 until 2026-09-30). */
  awakenDealt: 0.035,
  /** Awakening per point of damage taken (0.07 until 2026-09-30). */
  awakenTaken: 0.049,
  /** Awakening per Konpaku lost (15 until 2026-09-30). */
  awakenPerKonpaku: 10.5,
  /** Every awakening heals this fraction of max Reishi at once (the user 2026-09-30; before it only Nozarashi healed, 150). */
  awakenHeal: 0.2,
  /** Awakening cinematic (sim frozen; documentation only: the scripts own their :len). */
  awakenCineSeconds: 1.8,
  /** Stun frames per reaction. :launch / :knockdown are airborne / falling until they land (physics), then :down + :wakeup (iframes in both). */
  reactionFrames: { flinch: 18, stagger: 26, knockback: 30, launch: 0, knockdown: 0, 'guard-break': 50, crumple: 40, down: 30, wakeup: 30 },
  /** A grounded reaction's slide lasts at most this long. */
  knockbackSlideFrames: 18,
  /** Upward speed (m/s) given by a launch, a knockdown, and any other hit on an airborne fighter. */
  airVy: { launch: 7.5, knockdown: 3.5, air: 4.0 },
  /** An airborne reaction slides this x the hit's :kb (1 m without one) ... */
  airSlide: 0.6,
  /** ... over this many frames. */
  airSlideFrames: 20,
  /** Airborne fighters fall at this (m/s^2). */
  gravity: 22.0,
  /** A lunging move (:slide) stops moving this close to the opponent (1.3 until the J cut of 2026-09-29, docs/DUEL_STRINGS.md §13: a J reaches ~1 ... */
  lungeStop: 0.95,
  /** A follow-up link closes in at most this fast (m/s; the Kikon dash's speed) ... */
  chaseMax: 18.0,
  /** ... to this far inside its reach (never nearer than *LUNGE-STOP*) ... */
  chaseMargin: 0.4,
  /** ... turning toward him at least this fast (deg/s; a K link's own is 60). */
  chaseTrack: 360.0,
  /** Frames a move name stays above its user. */
  calloutFrames: 90,
  /** Launches per combo; a later launch becomes a knockback. */
  comboLaunches: 1,
  /** Airborne hits per combo; the last one knocks down. */
  comboAirHits: 3,
  /** Hits 1..this deal full damage... */
  comboFullHits: 3,
  /** ... then each hit deals this much less ... */
  comboDecay: 0.1,
  /** ... down to this fraction. */
  comboFloor: 0.4,
  /** Stun points a connected hit adds by its written reaction (any other: 1); :heavy is the floor of an SP / Kikon-rush strike. */
  stunWeights: { flinch: 1, bind: 1, stagger: 2, crumple: 3, knockback: 3, launch: 3, knockdown: 3, heavy: 3 },
  /** The stun a form without :stun-tolerance takes; the hit past it is the blow-away. */
  stunTolerance: 16.0,
  /** Frames after the last hit before the stun decays ... */
  stunDelay: 45,
  /** ... at this many points per second (never at once: a re-pin loop with gaps still fills it). */
  stunDecay: 6.0,
  /** The blow-away's knockdown :kb (x *AIR-SLIDE*: a ~5 m slide away from the attacker). */
  stunBlowKb: 8.0,
  /** Global hitstop of Quick hits. */
  hitstopLight: 4,
  /** Global hitstop of every other hit. */
  hitstopHeavy: 8,
  /** Global hitstop of a Breaker hit / Guard Break / clash. */
  hitstopBreaker: 10,
  /** Global hitstop of a blocked, armoured or absorbed hit. */
  hitstopBlock: 3,
  /** SP start: frames of the rim-light super flash... */
  superFlash: 6,
  /** ... and frames the opponent alone is frozen. */
  superFreeze: 4,
  /** Circular arena; fighters are clamped inside (invisible wall). */
  arenaRadius: 15.0,
  /** Burst Reverse (mod + Quick, *FS-BURST* flash-step) only in hitstun / airborne after this many hits of a combo (critique-design 1.7: not from ... */
  burstMinHits: 2,
  /** Frames the Burst user stays invulnerable (he is neutral at once). */
  burstInvuln: 20,
  /** Burst pushes the attacker this far (no stun; his move ends) ... */
  burstPush: 5.0,
  /** ... over this many frames. */
  burstPushFrames: 20,
  /** Global hitstop of a Burst. */
  burstHitstop: 8,
  /** Flash-step per second a running burst drains (100 -> 0 in 5.6 s, 70 in 3.9 s). */
  burstDrain: 18.0,
  /** WHITE (and the awakening's regen): Reishi regenerated per second (integer points; 12 -> 24 -> 70, the user 2026-09-30: a full-length run, 5. ... */
  whiteReishi: 70.0,
  /** WHITE: Reiatsu per second on top of *REIATSU-REGEN*. */
  whiteReiatsu: 15.0,
  /** WHITE: awakening gauge per second (2.0 x the slower gauge's 0.7). */
  whiteAwaken: 1.4,
  /** BLUE: the guard gauge's normal refill rate x this (no delay) when not guarding ... */
  blueGgMult: 2.0,
  /** ... and x this even while guarding (GUARD HOLD stops it otherwise). */
  blueGgGuarding: 0.5,
  /** ORANGE: frames after the cancel in which the next move started has its startup cut ... */
  chainWindow: 12,
  /** ... by this fraction (at least 1 f of startup left). */
  chainCut: 0.4,
  /** ORANGE: Reiatsu from hits dealt and KOSEI, awakening from hits dealt, x this. */
  orangeGain: 1.5,
  /** A Kikon that connects (or a Soul Break: the user 2026-09-30) gives its user this flash-step (one of the burst's two bars) ... */
  kikonFsRefund: 35.0,
  /** ... and this Reiatsu (one bar); after any burst ended. */
  kikonReiatsuRefund: 100.0,
  /** Damage x in Hellfire (Gokuen). */
  hellfireMult: 1.3,
  /** Damage x in Nozarashi's first cup, KATATE (v2: x1.15 before the ladder). */
  nozarashiMult: 1.0,
  /** Damage x in the second cup, RYOTE. */
  ryoteMult: 1.15,
  /** Damage x in the third cup, NOMIHOSE. */
  nomihoseMult: 1.2,
  /** Damage x Bankai East takes (the defender's :taken): the extreme stance. The Bankai rework (the user's spec 2026-09-27, docs/DUEL_YAMA_REWORK ... */
  bankaiTaken: 1.5,
  /** Bankai East's guard gauge refills at this x of everyone's rate (the user 2026-09-30, 「大幅降低山本『東 旭日刃』時的 防禦量表恢復速度」: x0.5, then 「破防後恢復速度不變，但東的恢復 ... */
  eastGgRegen: 0.25,
  /** Bankai East's pierce (passive :pierce, rules PIERCE-RATE): k = this at an empty guard gauge ... */
  pierceMin: 0.1,
  /** ... rising linearly to this at a full one (the user's decision 2026-09-27: full gauge = sharpest). A hit deals x(1 + k); a blocked hit lets  ... */
  pierceMax: 0.45,
  /** Bankai West's ward (passive :ward): a hit it blocks drains this x its guard value (after Kenpachi's cut). The main YK balance knob of the re ... */
  wardMult: 1.1,
  /** Cornered: + this damage fraction per Konpaku lost ... */
  corneredPerKonpaku: 0.05,
  /** ... up to this. */
  corneredMax: 0.25,
  /** Inferno (Goen) gauge; full -> Hellfire. */
  infernoMax: 100.0,
  /** Inferno per Flash hit. */
  infernoFlash: 20.0,
  /** Inferno per Signature hit (the cuts and the wave). */
  infernoSig: 15.0,
  /** Kit meter (Inferno) for a blocked hazard that gains meter on hit (wave, Shiranui). */
  meterOnBlock: 5.0,
  /** Hellfire length (the Inferno bar drains over it). */
  hellfireSeconds: 10.0,
  /** Hellfire burns this fraction of max Reishi per second (floor 1). */
  hellfireBurn: 0.05,
  /** Ennetsu Jigoku (Hellfire entry) pillar damage per hit... */
  ennetsuDamage: 60,
  /** ... at most this many hits ... */
  ennetsuHits: 2,
  /** ... and it burns the caster for this (floor 1). */
  ennetsuSelfBurn: 30,
  /** Pillars in the Ennetsu ring. */
  ennetsuPillars: 7,
  /** Ennetsu duration. */
  ennetsuSeconds: 0.8,
  /** West (:scorch): a melee hit his parry catches burns the attacker this much (never kills; the parry also refills his guard gauge: the rework) ... */
  scorch: 15,
  /** GOKUI GAESHI: the move frames (inclusive) its parry catches a melee hit (f2-25, KUSARI-TATE's window: the user 2026-10-01; was f4-15) ... */
  parryWindow: [2, 25],
  /** ... the parried attacker staggers this long (his move ends) ... */
  parryStun: 32,
  /** ... sliding this far. */
  parrySlide: 0.5,
  /** South (the bind): frames the victim's feet are held. Pacing knob (design v3 §E): 60 -> 45. */
  bindStun: 60,
  /** Nozarashi KATATE (cup 1): reach x of the inherited moves (1.4 before the ladder). */
  nozarashiReach: 1.3,
  /** Nozarashi KATATE (cup 1): extra startup frames of the inherited moves (3 before: F1->F2 was a 0 gap). */
  nozarashiStartup: 2,
  /** RYOTE (cup 2): reach x of the base moves it doesn't list. */
  ryoteReach: 1.4,
  /** RYOTE (cup 2): extra startup frames of the base moves it doesn't list. */
  ryoteStartup: 3,
  /** The NOME gauge. */
  nomeMax: 100.0,
  /** NOME at the awakening (cup 1). */
  nomeAwaken: 10.0,
  /** NOME per point of damage he deals ... */
  nomeDealt: 0.08,
  /** ... per point he loses (a drink's taken half too, the stance's absorbed points) ... */
  nomeTaken: 0.12,
  /** ... and per point drunk: a DRINK's swallowed half, all the stance absorbs. Knob: 0.30 -> 0.20. */
  nomeDrunk: 0.3,
  /** RYOTE drains only after this many frames without a gain (guard v3: 60 -> 180) ... */
  nomeDelay: 180,
  /** ... at this per second (guard v3: 3.0 -> 1.5; the user 2026-09-29: faster, x2 -> 3.0) ... */
  nomeDrainT2: 3.0,
  /** ... NOMIHOSE drains this per second, always (no delay; the user 2026-09-29: faster, x2, 10 -> 20). */
  nomeDrainT3: 20.0,
  /** Up to RYOTE at this ... */
  nomeUpT2: 40.0,
  /** ... back to KATATE below this ... */
  nomeDownT2: 25.0,
  /** ... up to NOMIHOSE at this ... */
  nomeUpT3: 100.0,
  /** ... back to RYOTE below this. */
  nomeDownT3: 50.0,
  /** NOMIHOSE: blade chip through guard. */
  nomihoseChip: 0.2,
  /** The cut (RYOTE and NOMIHOSE, passive :cut): his blocked Flash / Signature / SP hits drain this x their guard value (no gauge-paid armour is  ... */
  cutMult: 1.5,
  /** DRINK (NOMIHOSE's U): a drunk melee hit leaves the attacker this many frames worse off than a block. */
  drinkAdv: 4,
  /** KUKAN-GIRI: the rift it leaves cuts this many frames after its blade (f20 -> f40). Knob: 20 -> 18. */
  riftDelay: 20,
  /** Stance Signature: frames to enter the stance (hit = counter-hit). */
  stanceIn: 6,
  /** Longest stance hold before the cut comes out by itself. */
  stanceHoldMax: 60,
  /** Stance stores this x the damage it absorbs... */
  stanceStoreRate: 1.0,
  /** ... up to this. */
  stanceStoreCap: 200,
  /** Stance cut damage before the stored bonus. */
  stanceBaseDamage: 100,
  /** Stored >= this: the cut crushes guard. */
  stanceCrushAt: 150,
  /** Damage x in Kenpachi's Bankai. */
  bankaiKenMult: 1.2,
  /** Kenpachi may enter his Bankai (P in cup 3) with at most this many of his own Konpaku left (the user's decision 2026-09-28, replacing the red ... */
  bankaiKonpaku: 4,
  /** The arm meter UDE: pips at the Bankai's entry (the 4th spent: the arm bursts). */
  armPips: 4,
  /** A pip cracks by itself after this many frames without a spend (paused while locked): <= 20 s of Bankai. */
  armCrack: 300,
  /** Reishi each spent pip burns (BURN: never below 1). The design's 30 against a red Kenpachi; x2 now that the entry refills him to full (the us ... */
  armSelf: 60,
  /** Reishi the burst burns (the design's 60, x2 with the full refill). */
  armBurstSelf: 120,
  /** The burst's self-inflicted crumple, frames. */
  armBurstStun: 40,
  /** 片腕 KATAUDE: reach x of his sword moves (the kick, the Breaker and O as written). */
  kataudeReach: 0.7,
  /** Rukia's walk (Shikai). */
  walkRukia: 3.8,
  /** Damage x of the Shikai (the base kit's :mult; 58000+k at run time). The seed gate's lever: the CPU's Shikai fights the opponents' awakened f ... */
  rukiaMult: 1.5,
  /** ... and the damage it takes x this (60000+k). */
  rukiaTaken: 0.8,
  /** Damage x at -18 C (48000+k sets zero's, the colder-never-weaker lever) ... */
  rukiaAwakeMult: 1.15,
  /** ... at -50 C ... */
  rukiaM50Mult: 1.5,
  /** ... and at absolute zero (melee and ranged alike). */
  rukiaZeroMult: 1.65,
  /** Damage taken x at -18 C (61000+k scales every band) ... */
  rukiaAwakeTaken: 0.95,
  /** ... at -50 C (hardened) ... */
  rukiaM50Taken: 0.85,
  /** ... and at absolute zero (a ranged hit passes the ward: optic). */
  rukiaZeroTaken: 0.8,
  /** Rukia's run (Shikai). */
  runRukia: 9.0,
  /** -18 C: walk ... */
  walkM18: 3.4,
  /** ... and run. */
  runM18: 8.0,
  /** -50 C: walk ... */
  walkM50: 2.8,
  /** ... and run. Absolute zero: rooted (0). */
  runM50: 6.4,
  /** Frost: a frosted fighter walks and runs x this (Step, Hoho, lunges, dashes and frames untouched). */
  frostSlow: 0.7,
  /** Frost: the timer never exceeds this (a hit sets it to max(current, n): it never stacks). */
  frostCap: 150,
  /** -18 C: every real hit of hers frosts this long (the kit's :frost-touch; a hit window's own :frost wins if longer) ... */
  frostTouch: 30,
  /** ... at -50 C ... */
  frostTouchM50: 60,
  /** ... at absolute zero. */
  frostTouchZero: 90,
  /** The cold gauge: two stacked bars of *COLD-BAR* (the user's decision 2026-09-28). */
  coldMax: 200.0,
  /** One bar of cold. -18 -> -50 when C reaches it, -50 -> -18 when C falls to 0; -50 -> zero when C reaches *COLD-MAX*, zero -> -50 when C falls ... */
  coldBar: 100.0,
  /** Cold per second while she guards (the GUARD HOLD test; bracing at zero): a bar in 1.1 s, -18 -> zero in 2.2 s (the user's decision 2026-09-2 ... */
  ruCoolRate: 90.0,
  /** A blocked melee hit cools her this x its guard value (x1.5 with the faster cooling; 62000+k: x0.01). */
  ruBlockCool: 1.5,
  /** A real hit taken warms her this x its damage (63000+k: x0.01). */
  ruHitWarm: 0.2,
  /** Warming, cold per second while she isn't guarding, at -18 C (a full bar: 10 s) ... */
  ruWarmM18: 10.0,
  /** ... at -50 C (a bar: 8.3 s) ... */
  ruWarmM50: 12.0,
  /** ... at absolute zero, the slowest (the user's decision 2026-09-28: zero is easier to hold; half of -18's; unbraced 20 s to warm the top bar  ... */
  ruWarmZero: 5.0,
  /** Cold each command spends at -18 C (the user's decision: only L; refused below its cost) ... */
  ruColdM18: { sig: 25 },
  /** ... at -50 C (a Hoho adds cold: rukia.lisp *RU-HOHO-COLD*) ... */
  ruColdM50: { q: 6, f: 12, sig: 36, sp1: 40, sp2: 40, kikon: 20, breaker: 20, step: 12 },
  /** ... and at absolute zero (L and the SPs cash the whole top bar: she drops to -50; J / K / O 15 / 30 / 50 -> 20 / 40 / 60 with the faster coo ... */
  ruColdZero: { q: 20, f: 40, sig: 100, sp1: 100, sp2: 100, kikon: 60 },
  /** The cold field 寒域 at -18 C: within :r m of her the opponent walks / runs away from her x :away, his away Step x :step ... */
  ruFieldM18: { r: 3.0, away: 0.85, step: 1.0 },
  /** ... at -50 C ... */
  ruFieldM50: { r: 4.0, away: 0.7, step: 0.9 },
  /** ... at absolute zero (65000+k: :away x0.01). */
  ruFieldZero: { r: 5.5, away: 0.55, step: 0.75 },
  /** The field x frost never slows the away walk below this (66000+k: x0.01). */
  fieldFloor: 0.45,
  /** Absolute zero: bracing (U held) stops the warming but drains the guard gauge this per second (44000+k). */
  zeroBraceDrain: 8.0,
  /** After a CRACK her guard doesn't cool for this many frames (51000+f). */
  ruThawLock: 120,
  /** The CRACK (the ward crushed or broken at zero) burns this much (never below 1) ... */
  crackSelf: 60,
  /** ... and crumples her in place this long when she isn't in a reaction already. */
  crackStun: 30,
  /** Absolute zero: the first melee hit the ward blocks freezes its attacker this long (once per zero visit; the design's 24 -> 18: the A/B). */
  freezeTouch: 18,
  /** Frames a multi-hit hazard (pillars) waits between two hits. */
  hazardRehit: 16,
  /** Fire wave box: half-height, half-length (half-width = its :width / 2). */
  waveBox: [1.2, 0.5],
  /** Ennetsu pillar cylinder: radius, height. */
  pillarSize: [0.7, 5.0],
  /** Pillars hit from this many frames after they erupt until this many before they end. */
  pillarWindow: [6, 8],
  /** Perception delay (frames) per difficulty. */
  aiDelay: { easy: 24, normal: 14, hard: 8 },
  /** Frames between intent re-picks. */
  aiRepick: 12,
  /** Chance a neutral decision is an attack, per intent (+ 0.04 per heat point, at most 0.9). */
  aiAggression: { pressure: 0.45, approach: 0.3, zone: 0.5, defend: 0.1 },
  /** Frames a CPU stays in DEFEND after a reaction / blockstun ends. */
  aiRespect: 120,
  /** Frames (+ 0..40 random) between two neutral decisions (attack / guard / wait): the CPU's tempo. */
  aiThink: { easy: 56, normal: 40, hard: 20 },
  /** A neutral guard is held this + 0..that frames. */
  aiGuardHold: [14, 20],
  /** The strafe direction is re-rolled every this + 0..that frames. */
  aiStrafeTime: [40, 80],
  /** Punish a recovering opponent whose advantage is at or below this. */
  aiPunishAdv: -8,
  /** Chance the CPU punishes, with Q1, a blocked move whose block advantage is <= *AI-PUNISH-ADV*. It feels its own blockstun (no perception dela ... */
  aiBlockPunishP: { easy: 0.25, normal: 0.6, hard: 0.9 },
  /** On hit, a string that can go on with J or K takes K this often (the design's 0.5; 0.3 at the seed gate: K links are the heavy ones). */
  aiStringFlashP: 0.3,
  /** The O ender (a completed string: a link-3 hit) on an opponent who isn't red, per string: a kit's :o-ender, else this (on a red one always).  ... */
  aiOEnder: 0.15,
  /** The CPU's L after a K link that hit, per hit (a kit's :ai :l-after-k; Rukia's Shikai, docs/DUEL_STRINGS.md §12). A pacing knob of the seed g ... */
  aiRuLAfterK: 0.05,
  /** The same in her awakened bands (the awaken A/B's knob: debug 73000+k sets it to k / 100). */
  aiRuLAfterKAwake: 0.1,
  /** A CPU who isn't red guards a Kikon rush's dash-in follow-up with this chance (the B1 knob: DUEL_STRINGS §6). */
  aiFollowGuardP: { easy: 0.6, normal: 0.85, hard: 0.95 },
  /** J beats K: an opponent's K link still >= S(J1) + 2 frames from its hit, within J1's reach: J1 with this chance. */
  aiJBeatsKP: { easy: 0.2, normal: 0.45, hard: 0.7 },
  /** J mashing (the user 2026-10-02): his J starts seen within this many frames ... */
  aiMashWindow: 120,
  /** ... at least this many (a J string is 3): he mashes J (AI-MASH-P). */
  aiMashStarts: 4,
  /** Against a J masher, J out of his blocked J with this chance (else *AI-J-BEATS-K-P*) ... */
  aiAntiMashJP: 0.9,
  /** ... and Hoho his coming J with at least this chance (2 x the kit's :hoho, at least this). */
  aiAntiMashHoho: 0.5,
  /** A string that ends on a hit with no link left (link 3, or a link the CPU doesn't go on from) is cancelled into SP2 with this chance, one rol ... */
  aiSpCancelP: 0.3,
  /** On block a string goes on with a K link only this x the kit's :block-string (a J link otherwise; never a K ender). */
  aiBlockKP: 0.15,
  /** KOSEI: a neutral decision attacks + this x (1 - its own guard gauge / max) more often. */
  aiKoseiAggression: 0.2,
  /** Breaker a guard held longer than this (0.4 s) ... */
  aiGuardBreakHold: 24,
  /** ... within this range ... */
  aiGuardBreakRange: 3.0,
  /** ... with this probability. */
  aiGuardBreakP: 0.4,
  /** Answer an incoming Breaker aura. */
  aiAntiBreakerP: { easy: 0.4, normal: 0.55, hard: 0.7 },
  /** ... seen within this range: Hoho (a bar), Q1 beyond ... */
  aiAntiBreakerRange: 5.0,
  /** ... this range, else a sideways Step (a Kikon rush). */
  aiAntiBreakerQ: 1.8,
  /** A Breaker's dash: J1 once it is within J1's reach + this (J beats I, docs/DUEL_STRINGS.md §14: the dash covers ~1.2-1.5 m in J1's startup, s ... */
  aiAntiBreakerJ: 1.4,
  /** Chance of a kit :react answer (Kenpachi's stance) to what triggers it. */
  aiReactP: 0.7,
  /** A committed opponent move is a threat within its reach + this. */
  aiThreatMargin: 1.5,
  /** An incoming projectile is 'seen' within this range. */
  aiProjectileRange: 7.0,
  /** Heat per second without dealing damage (reset by dealing any). */
  aiHeatRate: 1.5,
  /** Beyond this distance heat rises twice as fast (two zoners staring). */
  aiHeatFar: 6.0,
  /** Preferred range shrinks this much per heat point ... */
  aiHeatRange: 0.3,
  /** ... but never below this. */
  aiMinRange: 1.0,
  /** At this heat the Breaker weight doubles. */
  aiHeatBreaker: 8.0,
  /** Chance (one roll per combo) the CPU bursts once it is worth it (AI-BURST-WANTED-P), no sooner than its perception delay after the combo's *B ... */
  aiBurstP: { easy: 0.2, normal: 0.6, hard: 0.85 },
  /** Burst is worth it below this fraction of Reishi ... */
  aiBurstLow: 0.5,
  /** Chance a CPU whose string hit and can't go on (no further link) CHAIN-REVERSEs (ORANGE) and restarts it with Q1. */
  aiOrangeP: { easy: 0.1, normal: 0.25, hard: 0.4 },
  /** (0.15 -> 0.3 and 6 -> 5 m, the user 2026-09-30: use WHITE more) Chance per neutral decision a CPU behind on Reishi SOUL-REVERSEs (WHITE) ... */
  aiWhiteP: 0.3,
  /** ... behind by at least this fraction of its max Reishi ... */
  aiWhiteBehind: 0.15,
  /** ... and at least this far (m) from him. */
  aiWhiteRange: 5.0,
  /** Under this fraction of his max Reishi the CPU finishes with hits (the Soul Break: the Kikon count + 1), no Kikon rushn(2026-09-30, the base  ... */
  aiSbFinish: 0.08,
  /** The CPU dashes (the kit's :dash / :dash-back chance, at a neutral decision) when it stands this far outside its preferred range: toward it f ... */
  aiDashGap: 2.5,
  /** Longest the CPU holds a dash. */
  aiDashFrames: 70,
  /** Out of a hit (the user 2026-10-02: a CPU caught by J strings had no way out but a burst): on its first free step after a reaction or a wake- ... */
  aiWakeGuardP: { easy: 0.25, normal: 0.4, hard: 0.85 },
  /** Out of blocking a J masher's J that still recovers beyond our J1's reach: back-Step with this chance (AI-GAP-STEP-P). */
  aiGapStepP: { easy: 0.2, normal: 0.5, hard: 0.75 },
  /** Step -> J (the user 2026-10-02): at a neutral decision where a forward Step lands within J1's reach, Step in with this chance (AI-DECIDE) .. ... */
  aiStepInP: { easy: 0.05, normal: 0.12, hard: 0.25 },
  /** ... and out of any Step of ours that lands him within J1's reach + *AI-STEP-J-MARGIN* (he isn't mid-attack), J at Step f10 with this chance  ... */
  aiStepJP: { easy: 0.3, normal: 0.6, hard: 0.9 },
  /** (J1's own lunge closes a little more.) */
  aiStepJMargin: 0.1,
  /** ... held this long (his restarted string comes in it; then J out of it: J-BEATS-K-P). */
  aiWakeGuardFrames: 20,
  /** ... when he is within this many metres (as perceived). */
  aiWakeGuardRange: 3.0,
  /** In blockstun a CPU keeps holding Guard through the string with this chance per blocked hit, whatever its guard gauge (turtling mid-string is ... */
  aiHoldGuard: { easy: 0.97, normal: 0.92, hard: 0.8 },
  /** The CPU rushes a red opponent within its kit's :kikon-range (a stunned one at once) with this chance per neutral decision; one who isn't red ... */
  aiKikonP: 0.5,
  /** Scales every fire emitter's rate (0.5 if the perf gate fails). */
  fireDensity: 1.0,
};
// the Lisp's knobs are single floats (literals read as SINGLE-FLOAT): round every one to f32 so a comparison against a
// knob (a distance at *KIKON-TRIGGER*, a gauge at a threshold) decides as the Lisp's does. Integers stay exact.
// (the character files' own knob tables go through f32Deep too)
export function f32Deep<O>(o: O): O {
  const r = o as Record<string, unknown>;
  for (const k of Object.keys(r)) {
    const v = r[k];
    if (typeof v === 'number') r[k] = Math.fround(v);
    else if (v && typeof v === 'object') f32Deep(v);
  }
  return o;
}
f32Deep(T);
export type Tuning = typeof T;
