;; Read (not compile) engine + target sources; report target symbols that shadow ENGINE internals
;; (= a name the target uses but the engine doesn't export). Run through tools/pkgcheck.sh.
;; Usage: ecl --norc --load pkgcheck.lisp -- file...   (engine files first; root-relative)
(setf *default-pathname-defaults* (truename (merge-pathnames "../" (directory-namestring *load-truename*))))
(defvar *defined* (make-hash-table :test 'equal) "names defined by top-level forms of any file")
(defun note-defs (form)
  (when (and (consp form) (string= (package-name *package*) "ENGINE"))
    (case (car form)
      ((progn eval-when) (mapc #'note-defs (if (eq (car form) 'eval-when) (cddr form) (cdr form))))
      (defstruct (let* ((spec (second form)) (name (if (consp spec) (car spec) spec))
                        (opts (if (consp spec) (cdr spec)))
                        (cn (find :conc-name opts :key (lambda (o) (and (consp o) (car o)))))
                        (conc (if cn (string (or (second cn) "")) (format nil "~a-" name))))
                   (setf (gethash (symbol-name name) *defined*) t)
                   (dolist (sl (cddr form))
                     (let ((sn (if (consp sl) (car sl) sl)))
                       (when (symbolp sn) (setf (gethash (format nil "~a~a" conc sn) *defined*) t))))
                   (dolist (o opts) (when (and (consp o) (eq (car o) :constructor) (second o))
                                      (setf (gethash (symbol-name (second o)) *defined*) t)))
                   (setf (gethash (format nil "MAKE-~a" name) *defined*) t (gethash (format nil "~a-P" name) *defined*) t)))
      (t (when (and (symbolp (car form)) (search "DEF" (symbol-name (car form))) (symbolp (second form)) (second form))
           (setf (gethash (symbol-name (second form)) *defined*) t))))))
(defun read-file (f)
  (with-open-file (in f)
    (let ((*package* (find-package :cl-user)))
      (loop for form = (read in nil :eof) until (eq form :eof)
            do (when (consp form)
                 (case (car form)
                   (defpackage (eval form))
                   (in-package (setf *package* (find-package (second form))))
                   (defmacro (eval form) (note-defs form))
                   (t (note-defs form))))))))
(let ((files (cdr (member "--" ext:*command-args* :test #'string=))))
  (dolist (f files) (read-file f))
  (let ((eng (find-package :engine)) (hits nil))
    (dolist (p (list-all-packages))
      (unless (member (package-name p) '("ENGINE" "COMMON-LISP" "KEYWORD" "COMMON-LISP-USER") :test #'string=)
        (when (member eng (package-use-list p))
          (do-symbols (s p)
            (when (eq (symbol-package s) p)
              (multiple-value-bind (es st) (find-symbol (symbol-name s) eng)
                (when (and es (eq st :internal) (gethash (symbol-name s) *defined*)) (push (list (package-name p) (symbol-name s)) hits))))))))
    (format t "~&~d symbols that look like unexported ENGINE names (export them, or rename):~%~{  ~{~a::~a~}~%~}" (length hits) (sort hits #'string< :key #'second))))
(ext:quit 0)
