;; Read (not compile) engine + target sources and report what ECL compiles silently:
;;  1. target symbols that shadow ENGINE internals (= a name the target uses but the engine doesn't
;;     export: the call would go to an undefined function in the target's package);
;;  2. top-level DEF* forms in the target that define an ENGINE export (= silently redefine the
;;     engine's function/variable for that build);
;;  3. functions called (or #'referenced) but defined nowhere: ECL doesn't warn about undefined
;;     functions, so a typo or a deleted helper only fails when that line runs.
;; Run through tools/pkgcheck.sh.
;; Usage: ecl --norc --load pkgcheck.lisp -- file...   (engine files first; root-relative)
(setf *default-pathname-defaults* (truename (merge-pathnames "../" (directory-namestring *load-truename*))))
(defvar *defined* (make-hash-table :test 'equal) "names defined by top-level forms of any file")
(defun note-defs (form)
  (when (and (consp form) (string= (package-name *package*) "ENGINE"))
    (case (car form)
      ((progn eval-when) (mapc #'note-defs (if (eq (car form) 'eval-when) (cddr form) (cdr form))))
      (defstruct (let* ((spec (second form)) (name (if (consp spec) (car spec) spec))
                        (opts (if (consp spec) (cdr spec)))
                        (cn (find :conc-name opts :key (lambda (o) (and (consp o) (car o)))))
                        (conc (if cn (string (or (second cn) "")) (format nil "~a-" name))))
                   (setf (gethash (symbol-name name) *defined*) t)
                   (dolist (sl (cddr form))
                     (let ((sn (if (consp sl) (car sl) sl)))
                       (when (symbolp sn) (setf (gethash (format nil "~a~a" conc sn) *defined*) t))))
                   (dolist (o opts) (when (and (consp o) (eq (car o) :constructor) (second o))
                                      (setf (gethash (symbol-name (second o)) *defined*) t)))
                   (setf (gethash (format nil "MAKE-~a" name) *defined*) t (gethash (format nil "~a-P" name) *defined*) t)))
      (t (when (and (symbolp (car form)) (search "DEF" (symbol-name (car form))) (symbolp (second form)) (second form))
           (setf (gethash (symbol-name (second form)) *defined*) t))))))
(defvar *redefs* nil "(file def-form name) of target DEF* forms that name an ENGINE export")
(defun note-redefs (form file)
  (when (and (consp form) (symbolp (car form)))
    (if (member (car form) '(progn eval-when))
        (dolist (f (if (eq (car form) 'eval-when) (cddr form) (cdr form))) (note-redefs f file))
        (let ((name (if (consp (second form)) (car (second form)) (second form))))   ; (defstruct (name ...))
          (when (and (search "DEF" (symbol-name (car form))) name (symbolp name)
                     (eq (symbol-package name) (find-package :engine))
                     (eq (nth-value 1 (find-symbol (symbol-name name) :engine)) :external))
            (push (list file (symbol-name (car form)) (symbol-name name)) *redefs*))))))
(defvar *forms* nil "(form . file) of every top-level form read, in order")
(defun read-file (f)
  (with-open-file (in f)
    (let ((*package* (find-package :cl-user)))
      (loop for form = (read in nil :eof) until (eq form :eof)
            do (push (cons form f) *forms*)
               (when (consp form)
                 (case (car form)
                   (defpackage (eval form))
                   (in-package (setf *package* (find-package (second form))))
                   (defmacro (eval form) (note-defs form))
                   (t (note-defs form)
                      (unless (string= (package-name *package*) "ENGINE") (note-redefs form f)))))))))
;;; ---------------------------------------------------------------- 3. undefined functions
;;; Every symbol of a checked package (the engine and the targets) that appears as a function call
;;; (car of a form) or in #'... must be defined by some DEF* form, a DEFSTRUCT / DEFCOMPONENT
;;; accessor, or an FLET / LABELS / MACROLET (a global set: ponytail, not lexically scoped). The walk
;;; knows the binding forms of CL (LET, LOOP FOR ..., DESTRUCTURING-BIND, lambda lists, COND / CASE
;;; clauses, DECLARE), skips quoted data, and macroexpands the engine's / targets' own macros when it
;;; can (DEFCINE's local AT / DURING), else walks the macro form as written.
(defvar *fdefs* (make-hash-table :test 'eq) "symbols defined as functions / macros")
(defvar *calls* (make-hash-table :test 'eq) "symbol -> file of the first call")
(defvar *file* nil)
(defun checked-p (s)
  (and (symbolp s) s (symbol-package s)
       (not (member (package-name (symbol-package s)) '("COMMON-LISP" "KEYWORD" "SI" "SYSTEM" "FFI" "EXT" "MP" "CLOS" "C") :test #'string=))))
(defun fdef (s) (when (symbolp s) (setf (gethash s *fdefs*) t)))
(defun call (s) (when (and (checked-p s) (not (gethash s *calls*))) (setf (gethash s *calls*) *file*)))
(defun def-struct (form)
  (let* ((spec (second form)) (name (if (consp spec) (car spec) spec)) (opts (if (consp spec) (cdr spec)))
         (pkg (and (symbolp name) (symbol-package name))))
    (unless pkg (return-from def-struct nil))     ; a template: (defstruct (,name ...)) in a macro
  (let* ((pkg pkg)
         (cn (find :conc-name opts :key (lambda (o) (and (consp o) (car o)))))
         (conc (if cn (string (or (second cn) "")) (format nil "~a-" name))))
    (flet ((d (fmt &rest args) (fdef (intern (apply #'format nil fmt args) pkg))))
      (d "~a" name) (d "MAKE-~a" name) (d "~a-P" name) (d "COPY-~a" name)
      (dolist (o opts) (when (and (consp o) (eq (car o) :constructor) (second o)) (fdef (second o))))
      (dolist (sl (cddr form))
        (let ((sn (if (consp sl) (car sl) sl)))
          (when (and sn (symbolp sn)) (d "~a~a" conc sn) (when (consp sl) (walk (second sl))))))))))
(defun walk-lambda-list (ll)
  "Walk the default forms of lambda list LL ((var default) entries; nested lists recurse)."
  (loop for x on (if (listp ll) ll nil) while (consp x)
        do (let ((el (car x)))
             (when (consp el)
               (if (and (symbolp (car el)) (not (member (car el) lambda-list-keywords)))
                   (walk (second el))
                   (walk-lambda-list el))))))
(defun walk-body (forms) (loop for f on forms while (consp f) do (walk (car f))))
(defun walk (x)
  (when (consp x)
    (let ((h (car x)))
      (cond
        ((not (symbolp h)) (walk-body x))
        ((member h '(quote declare declaim in-package defpackage)))
        ((eq h 'function) (let ((f (second x))) (if (consp f) (walk f) (call f))))
        ((or (member h '(defun defmacro define-compiler-macro)) (string= (symbol-name h) "DEFUN-FAST"))
         (let ((n (second x))) (fdef (if (consp n) (second n) n)))
         (walk-lambda-list (third x)) (walk-body (cdddr x)))
        ((member h '(lambda)) (walk-lambda-list (second x)) (walk-body (cddr x)))
        ((member h '(defvar defparameter defconstant)) (walk (third x)))
        ((eq h 'defstruct) (def-struct x))
        ((string= (symbol-name h) "DEFCOMPONENT")
         (def-struct (list* 'defstruct (second x) (remove-if #'stringp (cddr x)))))
        ((member h '(let let* symbol-macrolet))
         (dolist (b (second x)) (when (consp b) (walk (second b)))) (walk-body (cddr x)))
        ((member h '(flet labels macrolet))
         (dolist (b (second x))
           (when (consp b)
             (fdef (car b)) (walk-lambda-list (second b)) (walk-body (cddr b))
             (when (and (eq h 'macrolet) (checked-p (car b)))   ; so the body's uses expand (DEFUN ,name ...)
               (ignore-errors (eval `(defmacro ,(car b) ,@(cdr b)))))))
         (walk-body (cddr x)))
        ((member h '(destructuring-bind multiple-value-bind)) (walk-body (cddr x)))
        ((member h '(dolist dotimes)) (walk-body (cdr (second x))) (walk-body (cddr x)))
        ((member h '(do do*))
         (dolist (b (second x)) (when (consp b) (walk-body (cdr b)))) (walk-body (third x)) (walk-body (cdddr x)))
        ((eq h 'cond) (dolist (c (cdr x)) (walk-body c)))
        ((member h '(case ecase ccase typecase etypecase)) (walk (second x)) (dolist (c (cddr x)) (walk-body (cdr c))))
        ((member h '(handler-case)) (walk (second x)) (dolist (c (cddr x)) (walk-body (cddr c))))
        ((eq h 'loop)                                     ; skip the variable pattern after FOR / AS / WITH / INTO
         (loop for prev = nil then cur for cur in (cdr x)
               unless (and (symbolp prev) prev (member (symbol-name prev) '("FOR" "AS" "WITH" "INTO") :test #'string=))
                 do (walk cur)))
        ((eq h 'ffi:c-inline) (walk-body (second x)))
        ((eq h 'ffi:clines))
        (t (call h)
           (let ((exp (and (macro-function h) (checked-p h)
                           (ignore-errors (let ((*package* (symbol-package h))) (macroexpand-1 x))))))
             (cond ((and exp (not (eq exp x))) (walk exp))
                   ((and (macro-function h) (consp (second x)))  ; unexpandable (WITH-x (vars ...) ((var init) ...) body):
                    (let ((rest (cddr x)))                      ; skip the spec and binding lists
                      (loop while (and (consp (car rest)) (consp (caar rest))) do (pop rest))
                      (walk-body rest)))
                   (t (walk-body (cdr x))))))))))
(defun report-undefined ()
  (dolist (entry (reverse *forms*))
    (let ((*file* (cdr entry))) (walk (car entry))))
  (let ((undef nil))
    (maphash (lambda (s f) (unless (or (gethash s *fdefs*) (fboundp s)) (push (list f (package-name (symbol-package s)) (symbol-name s)) undef)))
             *calls*)
    (format t "~&~d functions called but defined nowhere (a typo, or a deleted helper):~%~{  ~{~a: ~a::~a~}~%~}"
            (length undef) (sort undef #'string< :key #'third))
    (length undef)))

(let ((files (cdr (member "--" ext:*command-args* :test #'string=))))
  (dolist (f files) (read-file f))
  (let ((eng (find-package :engine)) (hits nil))
    (dolist (p (list-all-packages))
      (unless (member (package-name p) '("ENGINE" "COMMON-LISP" "KEYWORD" "COMMON-LISP-USER") :test #'string=)
        (when (member eng (package-use-list p))
          (do-symbols (s p)
            (when (eq (symbol-package s) p)
              (multiple-value-bind (es st) (find-symbol (symbol-name s) eng)
                (when (and es (eq st :internal) (gethash (symbol-name s) *defined*)) (push (list (package-name p) (symbol-name s)) hits))))))))
    (format t "~&~d symbols that look like unexported ENGINE names (export them, or rename):~%~{  ~{~a::~a~}~%~}" (length hits) (sort hits #'string< :key #'second))
    (format t "~&~d top-level definitions that redefine an ENGINE export (rename them):~%~{  ~{~a: (~a ~a ...)~}~%~}" (length *redefs*) (reverse *redefs*))
    (ext:quit (if (plusp (+ (length hits) (length *redefs*) (report-undefined))) 1 0))))
