// glyphs-gen.mjs: duel/lisp/glyphs.lisp (the Yuji Syuku brush outlines, OFL; licence in duel/FONT-LICENSE-YujiSyuku.txt)
// -> src/render/vfx/glyphs.ts. Run: node tools/glyphs-gen.mjs
import fs from 'node:fs';
const src = fs.readFileSync(new URL('../../duel/lisp/glyphs.lisp', import.meta.url), 'utf8');
// the subset the cards and the HUD use: ASCII and the kanji of render/vfx/card.ts's captions
const KEEP = "卍解野晒呑め、鬼魂城郭炎上天地灰尽残火の太刀月白初舞霞罸絶対零度決着時間切れ北腕";
const out = {};
for (const m of src.matchAll(/^\s*\((\d+) (\d+) ((?:\([\d ]+\)\s*)+)\)/gm))
  if (+m[1] < 128 || KEEP.includes(String.fromCodePoint(+m[1]))) out[String.fromCodePoint(+m[1])] = [+m[2], [...m[3].matchAll(/\(([\d ]+)\)/g)].map((p) => p[1].trim().split(/\s+/).map(Number))];
fs.writeFileSync(new URL('../src/render/vfx/glyphs.ts', import.meta.url),
  `// GENERATED by tools/glyphs-gen.mjs from duel/lisp/glyphs.lisp (do not edit): brush glyph outlines converted from the font
// Yuji Syuku (Copyright 2021 The Yuji Project Authors, SIL Open Font License 1.1, duel/FONT-LICENSE-YujiSyuku.txt; a
// Modified Version, not a font file). Per char: [advance, polygons x0 y0 x1 y1 ... in 1/1000 em, y down].
export const GLYPHS: Record<string, [number, number[][]]> = ${JSON.stringify(out)};\n`);
console.log(Object.keys(out).length, 'glyphs');
